# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.addresses_schema_address import AddressesSchemaAddress  # noqa: F401,E501
from swagger_server import util


class AddressesSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, address: List[AddressesSchemaAddress]=None):  # noqa: E501
        """AddressesSchema - a model defined in Swagger

        :param address: The address of this AddressesSchema.  # noqa: E501
        :type address: List[AddressesSchemaAddress]
        """
        self.swagger_types = {
            'address': List[AddressesSchemaAddress]
        }

        self.attribute_map = {
            'address': 'address'
        }

        self._address = address

    @classmethod
    def from_dict(cls, dikt) -> 'AddressesSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AddressesSchema of this AddressesSchema.  # noqa: E501
        :rtype: AddressesSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def address(self) -> List[AddressesSchemaAddress]:
        """Gets the address of this AddressesSchema.

        The list of configured IPv6 addresses on the interface.  # noqa: E501

        :return: The address of this AddressesSchema.
        :rtype: List[AddressesSchemaAddress]
        """
        return self._address

    @address.setter
    def address(self, address: List[AddressesSchemaAddress]):
        """Sets the address of this AddressesSchema.

        The list of configured IPv6 addresses on the interface.  # noqa: E501

        :param address: The address of this AddressesSchema.
        :type address: List[AddressesSchemaAddress]
        """

        self._address = address
