# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.aggregation_logical_config import AggregationLogicalConfig  # noqa: F401,E501
from swagger_server.models.aggregation_logical_state import AggregationLogicalState  # noqa: F401,E501
from swagger_server import util


class AggregationLogicalTopAggregation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: AggregationLogicalState=None, config: AggregationLogicalConfig=None):  # noqa: E501
        """AggregationLogicalTopAggregation - a model defined in Swagger

        :param state: The state of this AggregationLogicalTopAggregation.  # noqa: E501
        :type state: AggregationLogicalState
        :param config: The config of this AggregationLogicalTopAggregation.  # noqa: E501
        :type config: AggregationLogicalConfig
        """
        self.swagger_types = {
            'state': AggregationLogicalState,
            'config': AggregationLogicalConfig
        }

        self.attribute_map = {
            'state': 'state',
            'config': 'config'
        }

        self._state = state
        self._config = config

    @classmethod
    def from_dict(cls, dikt) -> 'AggregationLogicalTopAggregation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AggregationLogicalTop_aggregation of this AggregationLogicalTopAggregation.  # noqa: E501
        :rtype: AggregationLogicalTopAggregation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> AggregationLogicalState:
        """Gets the state of this AggregationLogicalTopAggregation.

        Operational state variables for logical aggregate / LAG interfaces  # noqa: E501

        :return: The state of this AggregationLogicalTopAggregation.
        :rtype: AggregationLogicalState
        """
        return self._state

    @state.setter
    def state(self, state: AggregationLogicalState):
        """Sets the state of this AggregationLogicalTopAggregation.

        Operational state variables for logical aggregate / LAG interfaces  # noqa: E501

        :param state: The state of this AggregationLogicalTopAggregation.
        :type state: AggregationLogicalState
        """

        self._state = state

    @property
    def config(self) -> AggregationLogicalConfig:
        """Gets the config of this AggregationLogicalTopAggregation.

        Configuration variables for logical aggregate / LAG interfaces  # noqa: E501

        :return: The config of this AggregationLogicalTopAggregation.
        :rtype: AggregationLogicalConfig
        """
        return self._config

    @config.setter
    def config(self, config: AggregationLogicalConfig):
        """Sets the config of this AggregationLogicalTopAggregation.

        Configuration variables for logical aggregate / LAG interfaces  # noqa: E501

        :param config: The config of this AggregationLogicalTopAggregation.
        :type config: AggregationLogicalConfig
        """

        self._config = config
