# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.vlan_logical_double_tagged_config import VlanLogicalDoubleTaggedConfig  # noqa: F401,E501
from swagger_server import util


class DoubleTaggedSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: VlanLogicalDoubleTaggedConfig=None, config: VlanLogicalDoubleTaggedConfig=None):  # noqa: E501
        """DoubleTaggedSchema - a model defined in Swagger

        :param state: The state of this DoubleTaggedSchema.  # noqa: E501
        :type state: VlanLogicalDoubleTaggedConfig
        :param config: The config of this DoubleTaggedSchema.  # noqa: E501
        :type config: VlanLogicalDoubleTaggedConfig
        """
        self.swagger_types = {
            'state': VlanLogicalDoubleTaggedConfig,
            'config': VlanLogicalDoubleTaggedConfig
        }

        self.attribute_map = {
            'state': 'state',
            'config': 'config'
        }

        self._state = state
        self._config = config

    @classmethod
    def from_dict(cls, dikt) -> 'DoubleTaggedSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DoubleTaggedSchema of this DoubleTaggedSchema.  # noqa: E501
        :rtype: DoubleTaggedSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> VlanLogicalDoubleTaggedConfig:
        """Gets the state of this DoubleTaggedSchema.

        State for matching double-tagged packets against inner exact and outer exact VLAN identifiers.  # noqa: E501

        :return: The state of this DoubleTaggedSchema.
        :rtype: VlanLogicalDoubleTaggedConfig
        """
        return self._state

    @state.setter
    def state(self, state: VlanLogicalDoubleTaggedConfig):
        """Sets the state of this DoubleTaggedSchema.

        State for matching double-tagged packets against inner exact and outer exact VLAN identifiers.  # noqa: E501

        :param state: The state of this DoubleTaggedSchema.
        :type state: VlanLogicalDoubleTaggedConfig
        """

        self._state = state

    @property
    def config(self) -> VlanLogicalDoubleTaggedConfig:
        """Gets the config of this DoubleTaggedSchema.

        Configuration for matching double-tagged packets against inner exact and outer exact VLAN identifiers.  # noqa: E501

        :return: The config of this DoubleTaggedSchema.
        :rtype: VlanLogicalDoubleTaggedConfig
        """
        return self._config

    @config.setter
    def config(self, config: VlanLogicalDoubleTaggedConfig):
        """Sets the config of this DoubleTaggedSchema.

        Configuration for matching double-tagged packets against inner exact and outer exact VLAN identifiers.  # noqa: E501

        :param config: The config of this DoubleTaggedSchema.
        :type config: VlanLogicalDoubleTaggedConfig
        """

        self._config = config
