# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.vlan_logical_double_tagged_outer_list_config import VlanLogicalDoubleTaggedOuterListConfig  # noqa: F401,E501
from swagger_server import util


class DoubleTaggedOuterListSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: VlanLogicalDoubleTaggedOuterListConfig=None, config: VlanLogicalDoubleTaggedOuterListConfig=None):  # noqa: E501
        """DoubleTaggedOuterListSchema - a model defined in Swagger

        :param state: The state of this DoubleTaggedOuterListSchema.  # noqa: E501
        :type state: VlanLogicalDoubleTaggedOuterListConfig
        :param config: The config of this DoubleTaggedOuterListSchema.  # noqa: E501
        :type config: VlanLogicalDoubleTaggedOuterListConfig
        """
        self.swagger_types = {
            'state': VlanLogicalDoubleTaggedOuterListConfig,
            'config': VlanLogicalDoubleTaggedOuterListConfig
        }

        self.attribute_map = {
            'state': 'state',
            'config': 'config'
        }

        self._state = state
        self._config = config

    @classmethod
    def from_dict(cls, dikt) -> 'DoubleTaggedOuterListSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DoubleTaggedOuterListSchema of this DoubleTaggedOuterListSchema.  # noqa: E501
        :rtype: DoubleTaggedOuterListSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> VlanLogicalDoubleTaggedOuterListConfig:
        """Gets the state of this DoubleTaggedOuterListSchema.

        State for matching double-tagged packets against an inner exact and outer list of VLAN identifiers.  # noqa: E501

        :return: The state of this DoubleTaggedOuterListSchema.
        :rtype: VlanLogicalDoubleTaggedOuterListConfig
        """
        return self._state

    @state.setter
    def state(self, state: VlanLogicalDoubleTaggedOuterListConfig):
        """Sets the state of this DoubleTaggedOuterListSchema.

        State for matching double-tagged packets against an inner exact and outer list of VLAN identifiers.  # noqa: E501

        :param state: The state of this DoubleTaggedOuterListSchema.
        :type state: VlanLogicalDoubleTaggedOuterListConfig
        """

        self._state = state

    @property
    def config(self) -> VlanLogicalDoubleTaggedOuterListConfig:
        """Gets the config of this DoubleTaggedOuterListSchema.

        Configuration for matching double-tagged packets against an inner exact and outer list of VLAN identifiers.  # noqa: E501

        :return: The config of this DoubleTaggedOuterListSchema.
        :rtype: VlanLogicalDoubleTaggedOuterListConfig
        """
        return self._config

    @config.setter
    def config(self, config: VlanLogicalDoubleTaggedOuterListConfig):
        """Sets the config of this DoubleTaggedOuterListSchema.

        Configuration for matching double-tagged packets against an inner exact and outer list of VLAN identifiers.  # noqa: E501

        :param config: The config of this DoubleTaggedOuterListSchema.
        :type config: VlanLogicalDoubleTaggedOuterListConfig
        """

        self._config = config
