# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.vlan_logical_double_tagged_inner_range_config import VlanLogicalDoubleTaggedInnerRangeConfig  # noqa: F401,E501
from swagger_server import util


class DoubleTaggedInnerRangeSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: VlanLogicalDoubleTaggedInnerRangeConfig=None, config: VlanLogicalDoubleTaggedInnerRangeConfig=None):  # noqa: E501
        """DoubleTaggedInnerRangeSchema - a model defined in Swagger

        :param state: The state of this DoubleTaggedInnerRangeSchema.  # noqa: E501
        :type state: VlanLogicalDoubleTaggedInnerRangeConfig
        :param config: The config of this DoubleTaggedInnerRangeSchema.  # noqa: E501
        :type config: VlanLogicalDoubleTaggedInnerRangeConfig
        """
        self.swagger_types = {
            'state': VlanLogicalDoubleTaggedInnerRangeConfig,
            'config': VlanLogicalDoubleTaggedInnerRangeConfig
        }

        self.attribute_map = {
            'state': 'state',
            'config': 'config'
        }

        self._state = state
        self._config = config

    @classmethod
    def from_dict(cls, dikt) -> 'DoubleTaggedInnerRangeSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DoubleTaggedInnerRangeSchema of this DoubleTaggedInnerRangeSchema.  # noqa: E501
        :rtype: DoubleTaggedInnerRangeSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> VlanLogicalDoubleTaggedInnerRangeConfig:
        """Gets the state of this DoubleTaggedInnerRangeSchema.

        State for matching double-tagged packets against an inner range and outer exact VLAN identifiers.  # noqa: E501

        :return: The state of this DoubleTaggedInnerRangeSchema.
        :rtype: VlanLogicalDoubleTaggedInnerRangeConfig
        """
        return self._state

    @state.setter
    def state(self, state: VlanLogicalDoubleTaggedInnerRangeConfig):
        """Sets the state of this DoubleTaggedInnerRangeSchema.

        State for matching double-tagged packets against an inner range and outer exact VLAN identifiers.  # noqa: E501

        :param state: The state of this DoubleTaggedInnerRangeSchema.
        :type state: VlanLogicalDoubleTaggedInnerRangeConfig
        """

        self._state = state

    @property
    def config(self) -> VlanLogicalDoubleTaggedInnerRangeConfig:
        """Gets the config of this DoubleTaggedInnerRangeSchema.

        Configuration for matching double-tagged packets against an inner range and outer exact VLAN identifiers.  # noqa: E501

        :return: The config of this DoubleTaggedInnerRangeSchema.
        :rtype: VlanLogicalDoubleTaggedInnerRangeConfig
        """
        return self._config

    @config.setter
    def config(self, config: VlanLogicalDoubleTaggedInnerRangeConfig):
        """Sets the config of this DoubleTaggedInnerRangeSchema.

        Configuration for matching double-tagged packets against an inner range and outer exact VLAN identifiers.  # noqa: E501

        :param config: The config of this DoubleTaggedInnerRangeSchema.
        :type config: VlanLogicalDoubleTaggedInnerRangeConfig
        """

        self._config = config
