# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.vlan_logical_double_tagged_inner_list_config import VlanLogicalDoubleTaggedInnerListConfig  # noqa: F401,E501
from swagger_server import util


class DoubleTaggedInnerListSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: VlanLogicalDoubleTaggedInnerListConfig=None, config: VlanLogicalDoubleTaggedInnerListConfig=None):  # noqa: E501
        """DoubleTaggedInnerListSchema - a model defined in Swagger

        :param state: The state of this DoubleTaggedInnerListSchema.  # noqa: E501
        :type state: VlanLogicalDoubleTaggedInnerListConfig
        :param config: The config of this DoubleTaggedInnerListSchema.  # noqa: E501
        :type config: VlanLogicalDoubleTaggedInnerListConfig
        """
        self.swagger_types = {
            'state': VlanLogicalDoubleTaggedInnerListConfig,
            'config': VlanLogicalDoubleTaggedInnerListConfig
        }

        self.attribute_map = {
            'state': 'state',
            'config': 'config'
        }

        self._state = state
        self._config = config

    @classmethod
    def from_dict(cls, dikt) -> 'DoubleTaggedInnerListSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DoubleTaggedInnerListSchema of this DoubleTaggedInnerListSchema.  # noqa: E501
        :rtype: DoubleTaggedInnerListSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> VlanLogicalDoubleTaggedInnerListConfig:
        """Gets the state of this DoubleTaggedInnerListSchema.

        State for matching double-tagged packets against an inner list and outer exact VLAN identifiers.  # noqa: E501

        :return: The state of this DoubleTaggedInnerListSchema.
        :rtype: VlanLogicalDoubleTaggedInnerListConfig
        """
        return self._state

    @state.setter
    def state(self, state: VlanLogicalDoubleTaggedInnerListConfig):
        """Sets the state of this DoubleTaggedInnerListSchema.

        State for matching double-tagged packets against an inner list and outer exact VLAN identifiers.  # noqa: E501

        :param state: The state of this DoubleTaggedInnerListSchema.
        :type state: VlanLogicalDoubleTaggedInnerListConfig
        """

        self._state = state

    @property
    def config(self) -> VlanLogicalDoubleTaggedInnerListConfig:
        """Gets the config of this DoubleTaggedInnerListSchema.

        Configuration for matching double-tagged packets against an inner list and outer exact VLAN identifiers.  # noqa: E501

        :return: The config of this DoubleTaggedInnerListSchema.
        :rtype: VlanLogicalDoubleTaggedInnerListConfig
        """
        return self._config

    @config.setter
    def config(self, config: VlanLogicalDoubleTaggedInnerListConfig):
        """Sets the config of this DoubleTaggedInnerListSchema.

        Configuration for matching double-tagged packets against an inner list and outer exact VLAN identifiers.  # noqa: E501

        :param config: The config of this DoubleTaggedInnerListSchema.
        :type config: VlanLogicalDoubleTaggedInnerListConfig
        """

        self._config = config
