# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.vlan_logical_egress_mapping_config import VlanLogicalEgressMappingConfig  # noqa: F401,E501
from swagger_server import util


class EgressMappingSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: VlanLogicalEgressMappingConfig=None, config: VlanLogicalEgressMappingConfig=None):  # noqa: E501
        """EgressMappingSchema - a model defined in Swagger

        :param state: The state of this EgressMappingSchema.  # noqa: E501
        :type state: VlanLogicalEgressMappingConfig
        :param config: The config of this EgressMappingSchema.  # noqa: E501
        :type config: VlanLogicalEgressMappingConfig
        """
        self.swagger_types = {
            'state': VlanLogicalEgressMappingConfig,
            'config': VlanLogicalEgressMappingConfig
        }

        self.attribute_map = {
            'state': 'state',
            'config': 'config'
        }

        self._state = state
        self._config = config

    @classmethod
    def from_dict(cls, dikt) -> 'EgressMappingSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EgressMappingSchema of this EgressMappingSchema.  # noqa: E501
        :rtype: EgressMappingSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> VlanLogicalEgressMappingConfig:
        """Gets the state of this EgressMappingSchema.

        State for engress VLAN stack behaviors for packets that are destined for output via this subinterface.  # noqa: E501

        :return: The state of this EgressMappingSchema.
        :rtype: VlanLogicalEgressMappingConfig
        """
        return self._state

    @state.setter
    def state(self, state: VlanLogicalEgressMappingConfig):
        """Sets the state of this EgressMappingSchema.

        State for engress VLAN stack behaviors for packets that are destined for output via this subinterface.  # noqa: E501

        :param state: The state of this EgressMappingSchema.
        :type state: VlanLogicalEgressMappingConfig
        """

        self._state = state

    @property
    def config(self) -> VlanLogicalEgressMappingConfig:
        """Gets the config of this EgressMappingSchema.

        Configuration for egress VLAN stack behaviors for packets that are destined for output via this subinterface.  # noqa: E501

        :return: The config of this EgressMappingSchema.
        :rtype: VlanLogicalEgressMappingConfig
        """
        return self._config

    @config.setter
    def config(self, config: VlanLogicalEgressMappingConfig):
        """Sets the config of this EgressMappingSchema.

        Configuration for egress VLAN stack behaviors for packets that are destined for output via this subinterface.  # noqa: E501

        :param config: The config of this EgressMappingSchema.
        :type config: VlanLogicalEgressMappingConfig
        """

        self._config = config
