# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ethernet_interface_config import EthernetInterfaceConfig  # noqa: F401,E501
from swagger_server.models.ethernet_interface_state import EthernetInterfaceState  # noqa: F401,E501
from swagger_server import util


class EthernetTopEthernet(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: EthernetInterfaceState=None, config: EthernetInterfaceConfig=None):  # noqa: E501
        """EthernetTopEthernet - a model defined in Swagger

        :param state: The state of this EthernetTopEthernet.  # noqa: E501
        :type state: EthernetInterfaceState
        :param config: The config of this EthernetTopEthernet.  # noqa: E501
        :type config: EthernetInterfaceConfig
        """
        self.swagger_types = {
            'state': EthernetInterfaceState,
            'config': EthernetInterfaceConfig
        }

        self.attribute_map = {
            'state': 'state',
            'config': 'config'
        }

        self._state = state
        self._config = config

    @classmethod
    def from_dict(cls, dikt) -> 'EthernetTopEthernet':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EthernetTop_ethernet of this EthernetTopEthernet.  # noqa: E501
        :rtype: EthernetTopEthernet
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> EthernetInterfaceState:
        """Gets the state of this EthernetTopEthernet.

        State variables for Ethernet interfaces  # noqa: E501

        :return: The state of this EthernetTopEthernet.
        :rtype: EthernetInterfaceState
        """
        return self._state

    @state.setter
    def state(self, state: EthernetInterfaceState):
        """Sets the state of this EthernetTopEthernet.

        State variables for Ethernet interfaces  # noqa: E501

        :param state: The state of this EthernetTopEthernet.
        :type state: EthernetInterfaceState
        """

        self._state = state

    @property
    def config(self) -> EthernetInterfaceConfig:
        """Gets the config of this EthernetTopEthernet.

        Configuration data for ethernet interfaces  # noqa: E501

        :return: The config of this EthernetTopEthernet.
        :rtype: EthernetInterfaceConfig
        """
        return self._config

    @config.setter
    def config(self, config: EthernetInterfaceConfig):
        """Sets the config of this EthernetTopEthernet.

        Configuration data for ethernet interfaces  # noqa: E501

        :param config: The config of this EthernetTopEthernet.
        :type config: EthernetInterfaceConfig
        """

        self._config = config
