# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ethernet_interface_config import EthernetInterfaceConfig  # noqa: F401,E501
from swagger_server.models.ethernet_interface_state import EthernetInterfaceState  # noqa: F401,E501
from swagger_server.models.vlan_switched_top_switched_vlan import VlanSwitchedTopSwitchedVlan  # noqa: F401,E501
from swagger_server import util


class EthernetSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, switched_vlan: VlanSwitchedTopSwitchedVlan=None, state: EthernetInterfaceState=None, config: EthernetInterfaceConfig=None):  # noqa: E501
        """EthernetSchema - a model defined in Swagger

        :param switched_vlan: The switched_vlan of this EthernetSchema.  # noqa: E501
        :type switched_vlan: VlanSwitchedTopSwitchedVlan
        :param state: The state of this EthernetSchema.  # noqa: E501
        :type state: EthernetInterfaceState
        :param config: The config of this EthernetSchema.  # noqa: E501
        :type config: EthernetInterfaceConfig
        """
        self.swagger_types = {
            'switched_vlan': VlanSwitchedTopSwitchedVlan,
            'state': EthernetInterfaceState,
            'config': EthernetInterfaceConfig
        }

        self.attribute_map = {
            'switched_vlan': 'switchedVlan',
            'state': 'state',
            'config': 'config'
        }

        self._switched_vlan = switched_vlan
        self._state = state
        self._config = config

    @classmethod
    def from_dict(cls, dikt) -> 'EthernetSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EthernetSchema of this EthernetSchema.  # noqa: E501
        :rtype: EthernetSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def switched_vlan(self) -> VlanSwitchedTopSwitchedVlan:
        """Gets the switched_vlan of this EthernetSchema.


        :return: The switched_vlan of this EthernetSchema.
        :rtype: VlanSwitchedTopSwitchedVlan
        """
        return self._switched_vlan

    @switched_vlan.setter
    def switched_vlan(self, switched_vlan: VlanSwitchedTopSwitchedVlan):
        """Sets the switched_vlan of this EthernetSchema.


        :param switched_vlan: The switched_vlan of this EthernetSchema.
        :type switched_vlan: VlanSwitchedTopSwitchedVlan
        """

        self._switched_vlan = switched_vlan

    @property
    def state(self) -> EthernetInterfaceState:
        """Gets the state of this EthernetSchema.

        State variables for Ethernet interfaces  # noqa: E501

        :return: The state of this EthernetSchema.
        :rtype: EthernetInterfaceState
        """
        return self._state

    @state.setter
    def state(self, state: EthernetInterfaceState):
        """Sets the state of this EthernetSchema.

        State variables for Ethernet interfaces  # noqa: E501

        :param state: The state of this EthernetSchema.
        :type state: EthernetInterfaceState
        """

        self._state = state

    @property
    def config(self) -> EthernetInterfaceConfig:
        """Gets the config of this EthernetSchema.

        Configuration data for ethernet interfaces  # noqa: E501

        :return: The config of this EthernetSchema.
        :rtype: EthernetInterfaceConfig
        """
        return self._config

    @config.setter
    def config(self, config: EthernetInterfaceConfig):
        """Sets the config of this EthernetSchema.

        Configuration data for ethernet interfaces  # noqa: E501

        :param config: The config of this EthernetSchema.
        :type config: EthernetInterfaceConfig
        """

        self._config = config
