# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.interface_ref_state_container import InterfaceRefStateContainer  # noqa: F401,E501
from swagger_server import util


class InterfaceRefState(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, interface_ref: InterfaceRefStateContainer=None):  # noqa: E501
        """InterfaceRefState - a model defined in Swagger

        :param interface_ref: The interface_ref of this InterfaceRefState.  # noqa: E501
        :type interface_ref: InterfaceRefStateContainer
        """
        self.swagger_types = {
            'interface_ref': InterfaceRefStateContainer
        }

        self.attribute_map = {
            'interface_ref': 'interfaceRef'
        }

        self._interface_ref = interface_ref

    @classmethod
    def from_dict(cls, dikt) -> 'InterfaceRefState':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InterfaceRefState of this InterfaceRefState.  # noqa: E501
        :rtype: InterfaceRefState
        """
        return util.deserialize_model(dikt, cls)

    @property
    def interface_ref(self) -> InterfaceRefStateContainer:
        """Gets the interface_ref of this InterfaceRefState.

        Reference to an interface or subinterface  # noqa: E501

        :return: The interface_ref of this InterfaceRefState.
        :rtype: InterfaceRefStateContainer
        """
        return self._interface_ref

    @interface_ref.setter
    def interface_ref(self, interface_ref: InterfaceRefStateContainer):
        """Sets the interface_ref of this InterfaceRefState.

        Reference to an interface or subinterface  # noqa: E501

        :param interface_ref: The interface_ref of this InterfaceRefState.
        :type interface_ref: InterfaceRefStateContainer
        """

        self._interface_ref = interface_ref
