# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.interfaces_top_interfaces import InterfacesTopInterfaces  # noqa: F401,E501
from swagger_server import util


class InterfacesTop(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, interfaces: InterfacesTopInterfaces=None):  # noqa: E501
        """InterfacesTop - a model defined in Swagger

        :param interfaces: The interfaces of this InterfacesTop.  # noqa: E501
        :type interfaces: InterfacesTopInterfaces
        """
        self.swagger_types = {
            'interfaces': InterfacesTopInterfaces
        }

        self.attribute_map = {
            'interfaces': 'interfaces'
        }

        self._interfaces = interfaces

    @classmethod
    def from_dict(cls, dikt) -> 'InterfacesTop':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InterfacesTop of this InterfacesTop.  # noqa: E501
        :rtype: InterfacesTop
        """
        return util.deserialize_model(dikt, cls)

    @property
    def interfaces(self) -> InterfacesTopInterfaces:
        """Gets the interfaces of this InterfacesTop.


        :return: The interfaces of this InterfacesTop.
        :rtype: InterfacesTopInterfaces
        """
        return self._interfaces

    @interfaces.setter
    def interfaces(self, interfaces: InterfacesTopInterfaces):
        """Sets the interfaces of this InterfacesTop.


        :param interfaces: The interfaces of this InterfacesTop.
        :type interfaces: InterfacesTopInterfaces
        """

        self._interfaces = interfaces
