# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InterfaceRef(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, interface_ref: object=None):  # noqa: E501
        """InterfaceRef - a model defined in Swagger

        :param interface_ref: The interface_ref of this InterfaceRef.  # noqa: E501
        :type interface_ref: object
        """
        self.swagger_types = {
            'interface_ref': object
        }

        self.attribute_map = {
            'interface_ref': 'interfaceRef'
        }

        self._interface_ref = interface_ref

    @classmethod
    def from_dict(cls, dikt) -> 'InterfaceRef':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InterfaceRef of this InterfaceRef.  # noqa: E501
        :rtype: InterfaceRef
        """
        return util.deserialize_model(dikt, cls)

    @property
    def interface_ref(self) -> object:
        """Gets the interface_ref of this InterfaceRef.

        Reference to an interface or subinterface  # noqa: E501

        :return: The interface_ref of this InterfaceRef.
        :rtype: object
        """
        return self._interface_ref

    @interface_ref.setter
    def interface_ref(self, interface_ref: object):
        """Sets the interface_ref of this InterfaceRef.

        Reference to an interface or subinterface  # noqa: E501

        :param interface_ref: The interface_ref of this InterfaceRef.
        :type interface_ref: object
        """

        self._interface_ref = interface_ref
