# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ip_vrrp_tracking_config import IpVrrpTrackingConfig  # noqa: F401,E501
from swagger_server.models.ip_vrrp_tracking_state import IpVrrpTrackingState  # noqa: F401,E501
from swagger_server import util


class InterfaceTrackingSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: IpVrrpTrackingState=None, config: IpVrrpTrackingConfig=None):  # noqa: E501
        """InterfaceTrackingSchema - a model defined in Swagger

        :param state: The state of this InterfaceTrackingSchema.  # noqa: E501
        :type state: IpVrrpTrackingState
        :param config: The config of this InterfaceTrackingSchema.  # noqa: E501
        :type config: IpVrrpTrackingConfig
        """
        self.swagger_types = {
            'state': IpVrrpTrackingState,
            'config': IpVrrpTrackingConfig
        }

        self.attribute_map = {
            'state': 'state',
            'config': 'config'
        }

        self._state = state
        self._config = config

    @classmethod
    def from_dict(cls, dikt) -> 'InterfaceTrackingSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InterfaceTrackingSchema of this InterfaceTrackingSchema.  # noqa: E501
        :rtype: InterfaceTrackingSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> IpVrrpTrackingState:
        """Gets the state of this InterfaceTrackingSchema.

        Operational state data for VRRP interface tracking  # noqa: E501

        :return: The state of this InterfaceTrackingSchema.
        :rtype: IpVrrpTrackingState
        """
        return self._state

    @state.setter
    def state(self, state: IpVrrpTrackingState):
        """Sets the state of this InterfaceTrackingSchema.

        Operational state data for VRRP interface tracking  # noqa: E501

        :param state: The state of this InterfaceTrackingSchema.
        :type state: IpVrrpTrackingState
        """

        self._state = state

    @property
    def config(self) -> IpVrrpTrackingConfig:
        """Gets the config of this InterfaceTrackingSchema.

        Configuration data for VRRP interface tracking  # noqa: E501

        :return: The config of this InterfaceTrackingSchema.
        :rtype: IpVrrpTrackingConfig
        """
        return self._config

    @config.setter
    def config(self, config: IpVrrpTrackingConfig):
        """Sets the config of this InterfaceTrackingSchema.

        Configuration data for VRRP interface tracking  # noqa: E501

        :param config: The config of this InterfaceTrackingSchema.
        :type config: IpVrrpTrackingConfig
        """

        self._config = config
