# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InterfaceRefCommon(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, interface: str=None, subinterface: str=None):  # noqa: E501
        """InterfaceRefCommon - a model defined in Swagger

        :param interface: The interface of this InterfaceRefCommon.  # noqa: E501
        :type interface: str
        :param subinterface: The subinterface of this InterfaceRefCommon.  # noqa: E501
        :type subinterface: str
        """
        self.swagger_types = {
            'interface': str,
            'subinterface': str
        }

        self.attribute_map = {
            'interface': 'interface',
            'subinterface': 'subinterface'
        }

        self._interface = interface
        self._subinterface = subinterface

    @classmethod
    def from_dict(cls, dikt) -> 'InterfaceRefCommon':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InterfaceRefCommon of this InterfaceRefCommon.  # noqa: E501
        :rtype: InterfaceRefCommon
        """
        return util.deserialize_model(dikt, cls)

    @property
    def interface(self) -> str:
        """Gets the interface of this InterfaceRefCommon.

        Reference to a base interface.  If a reference to a subinterface is required, this leaf must be specified to indicate the base interface.  # noqa: E501

        :return: The interface of this InterfaceRefCommon.
        :rtype: str
        """
        return self._interface

    @interface.setter
    def interface(self, interface: str):
        """Sets the interface of this InterfaceRefCommon.

        Reference to a base interface.  If a reference to a subinterface is required, this leaf must be specified to indicate the base interface.  # noqa: E501

        :param interface: The interface of this InterfaceRefCommon.
        :type interface: str
        """

        self._interface = interface

    @property
    def subinterface(self) -> str:
        """Gets the subinterface of this InterfaceRefCommon.

        Reference to a subinterface -- this requires the base interface to be specified using the interface leaf in this container.  If only a reference to a base interface is requuired, this leaf should not be set.  # noqa: E501

        :return: The subinterface of this InterfaceRefCommon.
        :rtype: str
        """
        return self._subinterface

    @subinterface.setter
    def subinterface(self, subinterface: str):
        """Sets the subinterface of this InterfaceRefCommon.

        Reference to a subinterface -- this requires the base interface to be specified using the interface leaf in this container.  If only a reference to a base interface is requuired, this leaf should not be set.  # noqa: E501

        :param subinterface: The subinterface of this InterfaceRefCommon.
        :type subinterface: str
        """

        self._subinterface = subinterface
