# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.interface_phys_holdtime_top_hold_time import InterfacePhysHoldtimeTopHoldTime  # noqa: F401,E501
from swagger_server import util


class InterfacePhysHoldtimeTop(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, hold_time: InterfacePhysHoldtimeTopHoldTime=None):  # noqa: E501
        """InterfacePhysHoldtimeTop - a model defined in Swagger

        :param hold_time: The hold_time of this InterfacePhysHoldtimeTop.  # noqa: E501
        :type hold_time: InterfacePhysHoldtimeTopHoldTime
        """
        self.swagger_types = {
            'hold_time': InterfacePhysHoldtimeTopHoldTime
        }

        self.attribute_map = {
            'hold_time': 'holdTime'
        }

        self._hold_time = hold_time

    @classmethod
    def from_dict(cls, dikt) -> 'InterfacePhysHoldtimeTop':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InterfacePhysHoldtimeTop of this InterfacePhysHoldtimeTop.  # noqa: E501
        :rtype: InterfacePhysHoldtimeTop
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hold_time(self) -> InterfacePhysHoldtimeTopHoldTime:
        """Gets the hold_time of this InterfacePhysHoldtimeTop.


        :return: The hold_time of this InterfacePhysHoldtimeTop.
        :rtype: InterfacePhysHoldtimeTopHoldTime
        """
        return self._hold_time

    @hold_time.setter
    def hold_time(self, hold_time: InterfacePhysHoldtimeTopHoldTime):
        """Sets the hold_time of this InterfacePhysHoldtimeTop.


        :param hold_time: The hold_time of this InterfacePhysHoldtimeTop.
        :type hold_time: InterfacePhysHoldtimeTopHoldTime
        """

        self._hold_time = hold_time
