# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InterfacesTopInterfaces(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, interface: List[object]=None):  # noqa: E501
        """InterfacesTopInterfaces - a model defined in Swagger

        :param interface: The interface of this InterfacesTopInterfaces.  # noqa: E501
        :type interface: List[object]
        """
        self.swagger_types = {
            'interface': List[object]
        }

        self.attribute_map = {
            'interface': 'interface'
        }

        self._interface = interface

    @classmethod
    def from_dict(cls, dikt) -> 'InterfacesTopInterfaces':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InterfacesTop_interfaces of this InterfacesTopInterfaces.  # noqa: E501
        :rtype: InterfacesTopInterfaces
        """
        return util.deserialize_model(dikt, cls)

    @property
    def interface(self) -> List[object]:
        """Gets the interface of this InterfacesTopInterfaces.

        The list of named interfaces on the device.  # noqa: E501

        :return: The interface of this InterfacesTopInterfaces.
        :rtype: List[object]
        """
        return self._interface

    @interface.setter
    def interface(self, interface: List[object]):
        """Sets the interface of this InterfacesTopInterfaces.

        The list of named interfaces on the device.  # noqa: E501

        :param interface: The interface of this InterfacesTopInterfaces.
        :type interface: List[object]
        """

        self._interface = interface
