# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ip_common_counters_state_counters import IpCommonCountersStateCounters  # noqa: F401,E501
from swagger_server import util


class IpCommonCountersState(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, counters: IpCommonCountersStateCounters=None):  # noqa: E501
        """IpCommonCountersState - a model defined in Swagger

        :param counters: The counters of this IpCommonCountersState.  # noqa: E501
        :type counters: IpCommonCountersStateCounters
        """
        self.swagger_types = {
            'counters': IpCommonCountersStateCounters
        }

        self.attribute_map = {
            'counters': 'counters'
        }

        self._counters = counters

    @classmethod
    def from_dict(cls, dikt) -> 'IpCommonCountersState':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IpCommonCountersState of this IpCommonCountersState.  # noqa: E501
        :rtype: IpCommonCountersState
        """
        return util.deserialize_model(dikt, cls)

    @property
    def counters(self) -> IpCommonCountersStateCounters:
        """Gets the counters of this IpCommonCountersState.


        :return: The counters of this IpCommonCountersState.
        :rtype: IpCommonCountersStateCounters
        """
        return self._counters

    @counters.setter
    def counters(self, counters: IpCommonCountersStateCounters):
        """Sets the counters of this IpCommonCountersState.


        :param counters: The counters of this IpCommonCountersState.
        :type counters: IpCommonCountersStateCounters
        """

        self._counters = counters
