# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IpVrrpIpv6Config(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, virtual_link_local: str=None):  # noqa: E501
        """IpVrrpIpv6Config - a model defined in Swagger

        :param virtual_link_local: The virtual_link_local of this IpVrrpIpv6Config.  # noqa: E501
        :type virtual_link_local: str
        """
        self.swagger_types = {
            'virtual_link_local': str
        }

        self.attribute_map = {
            'virtual_link_local': 'virtualLinkLocal'
        }

        self._virtual_link_local = virtual_link_local

    @classmethod
    def from_dict(cls, dikt) -> 'IpVrrpIpv6Config':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IpVrrpIpv6Config of this IpVrrpIpv6Config.  # noqa: E501
        :rtype: IpVrrpIpv6Config
        """
        return util.deserialize_model(dikt, cls)

    @property
    def virtual_link_local(self) -> str:
        """Gets the virtual_link_local of this IpVrrpIpv6Config.

        For VRRP on IPv6 interfaces, sets the virtual link local address  # noqa: E501

        :return: The virtual_link_local of this IpVrrpIpv6Config.
        :rtype: str
        """
        return self._virtual_link_local

    @virtual_link_local.setter
    def virtual_link_local(self, virtual_link_local: str):
        """Sets the virtual_link_local of this IpVrrpIpv6Config.

        For VRRP on IPv6 interfaces, sets the virtual link local address  # noqa: E501

        :param virtual_link_local: The virtual_link_local of this IpVrrpIpv6Config.
        :type virtual_link_local: str
        """

        self._virtual_link_local = virtual_link_local
