# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IpVrrpState(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, current_priority: str=None):  # noqa: E501
        """IpVrrpState - a model defined in Swagger

        :param current_priority: The current_priority of this IpVrrpState.  # noqa: E501
        :type current_priority: str
        """
        self.swagger_types = {
            'current_priority': str
        }

        self.attribute_map = {
            'current_priority': 'currentPriority'
        }

        self._current_priority = current_priority

    @classmethod
    def from_dict(cls, dikt) -> 'IpVrrpState':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IpVrrpState of this IpVrrpState.  # noqa: E501
        :rtype: IpVrrpState
        """
        return util.deserialize_model(dikt, cls)

    @property
    def current_priority(self) -> str:
        """Gets the current_priority of this IpVrrpState.

        Operational value of the priority for the interface in the VRRP group  # noqa: E501

        :return: The current_priority of this IpVrrpState.
        :rtype: str
        """
        return self._current_priority

    @current_priority.setter
    def current_priority(self, current_priority: str):
        """Sets the current_priority of this IpVrrpState.

        Operational value of the priority for the interface in the VRRP group  # noqa: E501

        :param current_priority: The current_priority of this IpVrrpState.
        :type current_priority: str
        """

        self._current_priority = current_priority
