# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ip_vrrp_tracking_top_interface_tracking import IpVrrpTrackingTopInterfaceTracking  # noqa: F401,E501
from swagger_server import util


class IpVrrpTrackingTop(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, interface_tracking: IpVrrpTrackingTopInterfaceTracking=None):  # noqa: E501
        """IpVrrpTrackingTop - a model defined in Swagger

        :param interface_tracking: The interface_tracking of this IpVrrpTrackingTop.  # noqa: E501
        :type interface_tracking: IpVrrpTrackingTopInterfaceTracking
        """
        self.swagger_types = {
            'interface_tracking': IpVrrpTrackingTopInterfaceTracking
        }

        self.attribute_map = {
            'interface_tracking': 'interfaceTracking'
        }

        self._interface_tracking = interface_tracking

    @classmethod
    def from_dict(cls, dikt) -> 'IpVrrpTrackingTop':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IpVrrpTrackingTop of this IpVrrpTrackingTop.  # noqa: E501
        :rtype: IpVrrpTrackingTop
        """
        return util.deserialize_model(dikt, cls)

    @property
    def interface_tracking(self) -> IpVrrpTrackingTopInterfaceTracking:
        """Gets the interface_tracking of this IpVrrpTrackingTop.


        :return: The interface_tracking of this IpVrrpTrackingTop.
        :rtype: IpVrrpTrackingTopInterfaceTracking
        """
        return self._interface_tracking

    @interface_tracking.setter
    def interface_tracking(self, interface_tracking: IpVrrpTrackingTopInterfaceTracking):
        """Sets the interface_tracking of this IpVrrpTrackingTop.


        :param interface_tracking: The interface_tracking of this IpVrrpTrackingTop.
        :type interface_tracking: IpVrrpTrackingTopInterfaceTracking
        """

        self._interface_tracking = interface_tracking
