# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ip_vrrp_top_vrrp import IpVrrpTopVrrp  # noqa: F401,E501
from swagger_server import util


class IpVrrpTop(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, vrrp: IpVrrpTopVrrp=None):  # noqa: E501
        """IpVrrpTop - a model defined in Swagger

        :param vrrp: The vrrp of this IpVrrpTop.  # noqa: E501
        :type vrrp: IpVrrpTopVrrp
        """
        self.swagger_types = {
            'vrrp': IpVrrpTopVrrp
        }

        self.attribute_map = {
            'vrrp': 'vrrp'
        }

        self._vrrp = vrrp

    @classmethod
    def from_dict(cls, dikt) -> 'IpVrrpTop':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IpVrrpTop of this IpVrrpTop.  # noqa: E501
        :rtype: IpVrrpTop
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vrrp(self) -> IpVrrpTopVrrp:
        """Gets the vrrp of this IpVrrpTop.


        :return: The vrrp of this IpVrrpTop.
        :rtype: IpVrrpTopVrrp
        """
        return self._vrrp

    @vrrp.setter
    def vrrp(self, vrrp: IpVrrpTopVrrp):
        """Sets the vrrp of this IpVrrpTop.


        :param vrrp: The vrrp of this IpVrrpTop.
        :type vrrp: IpVrrpTopVrrp
        """

        self._vrrp = vrrp
