# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IpVrrpTopVrrp(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, vrrp_group: List[object]=None):  # noqa: E501
        """IpVrrpTopVrrp - a model defined in Swagger

        :param vrrp_group: The vrrp_group of this IpVrrpTopVrrp.  # noqa: E501
        :type vrrp_group: List[object]
        """
        self.swagger_types = {
            'vrrp_group': List[object]
        }

        self.attribute_map = {
            'vrrp_group': 'vrrpGroup'
        }

        self._vrrp_group = vrrp_group

    @classmethod
    def from_dict(cls, dikt) -> 'IpVrrpTopVrrp':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IpVrrpTop_vrrp of this IpVrrpTopVrrp.  # noqa: E501
        :rtype: IpVrrpTopVrrp
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vrrp_group(self) -> List[object]:
        """Gets the vrrp_group of this IpVrrpTopVrrp.

        List of VRRP groups, keyed by virtual router id  # noqa: E501

        :return: The vrrp_group of this IpVrrpTopVrrp.
        :rtype: List[object]
        """
        return self._vrrp_group

    @vrrp_group.setter
    def vrrp_group(self, vrrp_group: List[object]):
        """Sets the vrrp_group of this IpVrrpTopVrrp.

        List of VRRP groups, keyed by virtual router id  # noqa: E501

        :param vrrp_group: The vrrp_group of this IpVrrpTopVrrp.
        :type vrrp_group: List[object]
        """

        self._vrrp_group = vrrp_group
