# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ip_common_global_config import IpCommonGlobalConfig  # noqa: F401,E501
from swagger_server import util


class Ipv4GlobalConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, dhcp_client: bool=None, enabled: bool=None, mtu: str=None):  # noqa: E501
        """Ipv4GlobalConfig - a model defined in Swagger

        :param dhcp_client: The dhcp_client of this Ipv4GlobalConfig.  # noqa: E501
        :type dhcp_client: bool
        :param enabled: The enabled of this Ipv4GlobalConfig.  # noqa: E501
        :type enabled: bool
        :param mtu: The mtu of this Ipv4GlobalConfig.  # noqa: E501
        :type mtu: str
        """
        self.swagger_types = {
            'dhcp_client': bool,
            'enabled': bool,
            'mtu': str
        }

        self.attribute_map = {
            'dhcp_client': 'dhcpClient',
            'enabled': 'enabled',
            'mtu': 'mtu'
        }

        self._dhcp_client = dhcp_client
        self._enabled = enabled
        self._mtu = mtu

    @classmethod
    def from_dict(cls, dikt) -> 'Ipv4GlobalConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Ipv4GlobalConfig of this Ipv4GlobalConfig.  # noqa: E501
        :rtype: Ipv4GlobalConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dhcp_client(self) -> bool:
        """Gets the dhcp_client of this Ipv4GlobalConfig.

        Enables a DHCP client on the interface in order to request an address  # noqa: E501

        :return: The dhcp_client of this Ipv4GlobalConfig.
        :rtype: bool
        """
        return self._dhcp_client

    @dhcp_client.setter
    def dhcp_client(self, dhcp_client: bool):
        """Sets the dhcp_client of this Ipv4GlobalConfig.

        Enables a DHCP client on the interface in order to request an address  # noqa: E501

        :param dhcp_client: The dhcp_client of this Ipv4GlobalConfig.
        :type dhcp_client: bool
        """

        self._dhcp_client = dhcp_client

    @property
    def enabled(self) -> bool:
        """Gets the enabled of this Ipv4GlobalConfig.

        Controls whether IPv4 is enabled or disabled on this interface.  When IPv4 is enabled, this interface is connected to an IPv4 stack, and the interface can send and receive IPv4 packets.  # noqa: E501

        :return: The enabled of this Ipv4GlobalConfig.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled: bool):
        """Sets the enabled of this Ipv4GlobalConfig.

        Controls whether IPv4 is enabled or disabled on this interface.  When IPv4 is enabled, this interface is connected to an IPv4 stack, and the interface can send and receive IPv4 packets.  # noqa: E501

        :param enabled: The enabled of this Ipv4GlobalConfig.
        :type enabled: bool
        """

        self._enabled = enabled

    @property
    def mtu(self) -> str:
        """Gets the mtu of this Ipv4GlobalConfig.

        The size, in octets, of the largest IPv4 packet that the interface will send and receive.  The server may restrict the allowed values for this leaf, depending on the interface's type.  If this leaf is not configured, the operationally used MTU depends on the interface's type.  # noqa: E501

        :return: The mtu of this Ipv4GlobalConfig.
        :rtype: str
        """
        return self._mtu

    @mtu.setter
    def mtu(self, mtu: str):
        """Sets the mtu of this Ipv4GlobalConfig.

        The size, in octets, of the largest IPv4 packet that the interface will send and receive.  The server may restrict the allowed values for this leaf, depending on the interface's type.  If this leaf is not configured, the operationally used MTU depends on the interface's type.  # noqa: E501

        :param mtu: The mtu of this Ipv4GlobalConfig.
        :type mtu: str
        """

        self._mtu = mtu
