# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Ipv6AddressState(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, origin: str=None, status: str=None):  # noqa: E501
        """Ipv6AddressState - a model defined in Swagger

        :param origin: The origin of this Ipv6AddressState.  # noqa: E501
        :type origin: str
        :param status: The status of this Ipv6AddressState.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'origin': str,
            'status': str
        }

        self.attribute_map = {
            'origin': 'origin',
            'status': 'status'
        }

        self._origin = origin
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Ipv6AddressState':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Ipv6AddressState of this Ipv6AddressState.  # noqa: E501
        :rtype: Ipv6AddressState
        """
        return util.deserialize_model(dikt, cls)

    @property
    def origin(self) -> str:
        """Gets the origin of this Ipv6AddressState.

        The origin of this address, e.g., static, dhcp, etc.  # noqa: E501

        :return: The origin of this Ipv6AddressState.
        :rtype: str
        """
        return self._origin

    @origin.setter
    def origin(self, origin: str):
        """Sets the origin of this Ipv6AddressState.

        The origin of this address, e.g., static, dhcp, etc.  # noqa: E501

        :param origin: The origin of this Ipv6AddressState.
        :type origin: str
        """
        allowed_values = ["OTHER", "STATIC", "DHCP", "LINK_LAYER", "RANDOM"]  # noqa: E501
        if origin not in allowed_values:
            raise ValueError(
                "Invalid value for `origin` ({0}), must be one of {1}"
                .format(origin, allowed_values)
            )

        self._origin = origin

    @property
    def status(self) -> str:
        """Gets the status of this Ipv6AddressState.

        The status of an address.  Most of the states correspond to states from the IPv6 Stateless Address Autoconfiguration protocol.  # noqa: E501

        :return: The status of this Ipv6AddressState.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Ipv6AddressState.

        The status of an address.  Most of the states correspond to states from the IPv6 Stateless Address Autoconfiguration protocol.  # noqa: E501

        :param status: The status of this Ipv6AddressState.
        :type status: str
        """
        allowed_values = ["PREFERRED", "DEPRECATED", "INVALID", "INACCESSIBLE", "UNKNOWN", "TENTATIVE", "DUPLICATE", "OPTIMISTIC"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
