# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Ipv6Top(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, ipv6: object=None):  # noqa: E501
        """Ipv6Top - a model defined in Swagger

        :param ipv6: The ipv6 of this Ipv6Top.  # noqa: E501
        :type ipv6: object
        """
        self.swagger_types = {
            'ipv6': object
        }

        self.attribute_map = {
            'ipv6': 'ipv6'
        }

        self._ipv6 = ipv6

    @classmethod
    def from_dict(cls, dikt) -> 'Ipv6Top':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Ipv6Top of this Ipv6Top.  # noqa: E501
        :rtype: Ipv6Top
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ipv6(self) -> object:
        """Gets the ipv6 of this Ipv6Top.

        Parameters for the IPv6 address family.  # noqa: E501

        :return: The ipv6 of this Ipv6Top.
        :rtype: object
        """
        return self._ipv6

    @ipv6.setter
    def ipv6(self, ipv6: object):
        """Sets the ipv6 of this Ipv6Top.

        Parameters for the IPv6 address family.  # noqa: E501

        :param ipv6: The ipv6 of this Ipv6Top.
        :type ipv6: object
        """

        self._ipv6 = ipv6
