# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Ipv6NeighborConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, ip: str=None, link_layer_address: str=None):  # noqa: E501
        """Ipv6NeighborConfig - a model defined in Swagger

        :param ip: The ip of this Ipv6NeighborConfig.  # noqa: E501
        :type ip: str
        :param link_layer_address: The link_layer_address of this Ipv6NeighborConfig.  # noqa: E501
        :type link_layer_address: str
        """
        self.swagger_types = {
            'ip': str,
            'link_layer_address': str
        }

        self.attribute_map = {
            'ip': 'ip',
            'link_layer_address': 'linkLayerAddress'
        }

        self._ip = ip
        self._link_layer_address = link_layer_address

    @classmethod
    def from_dict(cls, dikt) -> 'Ipv6NeighborConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Ipv6NeighborConfig of this Ipv6NeighborConfig.  # noqa: E501
        :rtype: Ipv6NeighborConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ip(self) -> str:
        """Gets the ip of this Ipv6NeighborConfig.

        The IPv6 address of the neighbor node.  # noqa: E501

        :return: The ip of this Ipv6NeighborConfig.
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip: str):
        """Sets the ip of this Ipv6NeighborConfig.

        The IPv6 address of the neighbor node.  # noqa: E501

        :param ip: The ip of this Ipv6NeighborConfig.
        :type ip: str
        """

        self._ip = ip

    @property
    def link_layer_address(self) -> str:
        """Gets the link_layer_address of this Ipv6NeighborConfig.

        The link-layer address of the neighbor node.  # noqa: E501

        :return: The link_layer_address of this Ipv6NeighborConfig.
        :rtype: str
        """
        return self._link_layer_address

    @link_layer_address.setter
    def link_layer_address(self, link_layer_address: str):
        """Sets the link_layer_address of this Ipv6NeighborConfig.

        The link-layer address of the neighbor node.  # noqa: E501

        :param link_layer_address: The link_layer_address of this Ipv6NeighborConfig.
        :type link_layer_address: str
        """

        self._link_layer_address = link_layer_address
