# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Ipv6RaConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, lifetime: str=None, interval: str=None, suppress: bool=None):  # noqa: E501
        """Ipv6RaConfig - a model defined in Swagger

        :param lifetime: The lifetime of this Ipv6RaConfig.  # noqa: E501
        :type lifetime: str
        :param interval: The interval of this Ipv6RaConfig.  # noqa: E501
        :type interval: str
        :param suppress: The suppress of this Ipv6RaConfig.  # noqa: E501
        :type suppress: bool
        """
        self.swagger_types = {
            'lifetime': str,
            'interval': str,
            'suppress': bool
        }

        self.attribute_map = {
            'lifetime': 'lifetime',
            'interval': 'interval',
            'suppress': 'suppress'
        }

        self._lifetime = lifetime
        self._interval = interval
        self._suppress = suppress

    @classmethod
    def from_dict(cls, dikt) -> 'Ipv6RaConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Ipv6RaConfig of this Ipv6RaConfig.  # noqa: E501
        :rtype: Ipv6RaConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lifetime(self) -> str:
        """Gets the lifetime of this Ipv6RaConfig.

        The lifetime advertised in the router advertisement neighbor discovery message on this interface.  # noqa: E501

        :return: The lifetime of this Ipv6RaConfig.
        :rtype: str
        """
        return self._lifetime

    @lifetime.setter
    def lifetime(self, lifetime: str):
        """Sets the lifetime of this Ipv6RaConfig.

        The lifetime advertised in the router advertisement neighbor discovery message on this interface.  # noqa: E501

        :param lifetime: The lifetime of this Ipv6RaConfig.
        :type lifetime: str
        """

        self._lifetime = lifetime

    @property
    def interval(self) -> str:
        """Gets the interval of this Ipv6RaConfig.

        The interval between periodic router advertisement neighbor discovery messages sent on this interface expressed in seconds.  # noqa: E501

        :return: The interval of this Ipv6RaConfig.
        :rtype: str
        """
        return self._interval

    @interval.setter
    def interval(self, interval: str):
        """Sets the interval of this Ipv6RaConfig.

        The interval between periodic router advertisement neighbor discovery messages sent on this interface expressed in seconds.  # noqa: E501

        :param interval: The interval of this Ipv6RaConfig.
        :type interval: str
        """

        self._interval = interval

    @property
    def suppress(self) -> bool:
        """Gets the suppress of this Ipv6RaConfig.

        When set to true, router advertisement neighbor discovery messages are not transmitted on this interface.  # noqa: E501

        :return: The suppress of this Ipv6RaConfig.
        :rtype: bool
        """
        return self._suppress

    @suppress.setter
    def suppress(self, suppress: bool):
        """Sets the suppress of this Ipv6RaConfig.

        When set to true, router advertisement neighbor discovery messages are not transmitted on this interface.  # noqa: E501

        :param suppress: The suppress of this Ipv6RaConfig.
        :type suppress: bool
        """

        self._suppress = suppress
