# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ipv4_proxy_arp_config import Ipv4ProxyArpConfig  # noqa: F401,E501
from swagger_server import util


class ProxyArpSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: Ipv4ProxyArpConfig=None, config: Ipv4ProxyArpConfig=None):  # noqa: E501
        """ProxyArpSchema - a model defined in Swagger

        :param state: The state of this ProxyArpSchema.  # noqa: E501
        :type state: Ipv4ProxyArpConfig
        :param config: The config of this ProxyArpSchema.  # noqa: E501
        :type config: Ipv4ProxyArpConfig
        """
        self.swagger_types = {
            'state': Ipv4ProxyArpConfig,
            'config': Ipv4ProxyArpConfig
        }

        self.attribute_map = {
            'state': 'state',
            'config': 'config'
        }

        self._state = state
        self._config = config

    @classmethod
    def from_dict(cls, dikt) -> 'ProxyArpSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProxyArpSchema of this ProxyArpSchema.  # noqa: E501
        :rtype: ProxyArpSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> Ipv4ProxyArpConfig:
        """Gets the state of this ProxyArpSchema.

        Operational state parameters for proxy ARP  # noqa: E501

        :return: The state of this ProxyArpSchema.
        :rtype: Ipv4ProxyArpConfig
        """
        return self._state

    @state.setter
    def state(self, state: Ipv4ProxyArpConfig):
        """Sets the state of this ProxyArpSchema.

        Operational state parameters for proxy ARP  # noqa: E501

        :param state: The state of this ProxyArpSchema.
        :type state: Ipv4ProxyArpConfig
        """

        self._state = state

    @property
    def config(self) -> Ipv4ProxyArpConfig:
        """Gets the config of this ProxyArpSchema.

        Configuration parameters for proxy ARP  # noqa: E501

        :return: The config of this ProxyArpSchema.
        :rtype: Ipv4ProxyArpConfig
        """
        return self._config

    @config.setter
    def config(self, config: Ipv4ProxyArpConfig):
        """Sets the config of this ProxyArpSchema.

        Configuration parameters for proxy ARP  # noqa: E501

        :param config: The config of this ProxyArpSchema.
        :type config: Ipv4ProxyArpConfig
        """

        self._config = config
