# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ipv6_ra_config import Ipv6RaConfig  # noqa: F401,E501
from swagger_server import util


class RouterAdvertisementSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: Ipv6RaConfig=None, config: Ipv6RaConfig=None):  # noqa: E501
        """RouterAdvertisementSchema - a model defined in Swagger

        :param state: The state of this RouterAdvertisementSchema.  # noqa: E501
        :type state: Ipv6RaConfig
        :param config: The config of this RouterAdvertisementSchema.  # noqa: E501
        :type config: Ipv6RaConfig
        """
        self.swagger_types = {
            'state': Ipv6RaConfig,
            'config': Ipv6RaConfig
        }

        self.attribute_map = {
            'state': 'state',
            'config': 'config'
        }

        self._state = state
        self._config = config

    @classmethod
    def from_dict(cls, dikt) -> 'RouterAdvertisementSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RouterAdvertisementSchema of this RouterAdvertisementSchema.  # noqa: E501
        :rtype: RouterAdvertisementSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> Ipv6RaConfig:
        """Gets the state of this RouterAdvertisementSchema.

        Operational state parameters relating to router advertisements for IPv6.  # noqa: E501

        :return: The state of this RouterAdvertisementSchema.
        :rtype: Ipv6RaConfig
        """
        return self._state

    @state.setter
    def state(self, state: Ipv6RaConfig):
        """Sets the state of this RouterAdvertisementSchema.

        Operational state parameters relating to router advertisements for IPv6.  # noqa: E501

        :param state: The state of this RouterAdvertisementSchema.
        :type state: Ipv6RaConfig
        """

        self._state = state

    @property
    def config(self) -> Ipv6RaConfig:
        """Gets the config of this RouterAdvertisementSchema.

        Configuration parameters relating to router advertisements for IPv6.  # noqa: E501

        :return: The config of this RouterAdvertisementSchema.
        :rtype: Ipv6RaConfig
        """
        return self._config

    @config.setter
    def config(self, config: Ipv6RaConfig):
        """Sets the config of this RouterAdvertisementSchema.

        Configuration parameters relating to router advertisements for IPv6.  # noqa: E501

        :param config: The config of this RouterAdvertisementSchema.
        :type config: Ipv6RaConfig
        """

        self._config = config
