# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SubUnnumberedConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, enabled: bool=None):  # noqa: E501
        """SubUnnumberedConfig - a model defined in Swagger

        :param enabled: The enabled of this SubUnnumberedConfig.  # noqa: E501
        :type enabled: bool
        """
        self.swagger_types = {
            'enabled': bool
        }

        self.attribute_map = {
            'enabled': 'enabled'
        }

        self._enabled = enabled

    @classmethod
    def from_dict(cls, dikt) -> 'SubUnnumberedConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SubUnnumberedConfig of this SubUnnumberedConfig.  # noqa: E501
        :rtype: SubUnnumberedConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def enabled(self) -> bool:
        """Gets the enabled of this SubUnnumberedConfig.

        Indicates that the subinterface is unnumbered.  By default the subinterface is numbered, i.e., expected to have an IP address configuration.  # noqa: E501

        :return: The enabled of this SubUnnumberedConfig.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled: bool):
        """Sets the enabled of this SubUnnumberedConfig.

        Indicates that the subinterface is unnumbered.  By default the subinterface is numbered, i.e., expected to have an IP address configuration.  # noqa: E501

        :param enabled: The enabled of this SubUnnumberedConfig.
        :type enabled: bool
        """

        self._enabled = enabled
