# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.subinterfaces_top_subinterfaces_subinterface import SubinterfacesTopSubinterfacesSubinterface  # noqa: F401,E501
from swagger_server import util


class SubinterfacesTopSubinterfaces(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, subinterface: List[SubinterfacesTopSubinterfacesSubinterface]=None):  # noqa: E501
        """SubinterfacesTopSubinterfaces - a model defined in Swagger

        :param subinterface: The subinterface of this SubinterfacesTopSubinterfaces.  # noqa: E501
        :type subinterface: List[SubinterfacesTopSubinterfacesSubinterface]
        """
        self.swagger_types = {
            'subinterface': List[SubinterfacesTopSubinterfacesSubinterface]
        }

        self.attribute_map = {
            'subinterface': 'subinterface'
        }

        self._subinterface = subinterface

    @classmethod
    def from_dict(cls, dikt) -> 'SubinterfacesTopSubinterfaces':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SubinterfacesTop_subinterfaces of this SubinterfacesTopSubinterfaces.  # noqa: E501
        :rtype: SubinterfacesTopSubinterfaces
        """
        return util.deserialize_model(dikt, cls)

    @property
    def subinterface(self) -> List[SubinterfacesTopSubinterfacesSubinterface]:
        """Gets the subinterface of this SubinterfacesTopSubinterfaces.

        The list of subinterfaces (logical interfaces) associated with a physical interface  # noqa: E501

        :return: The subinterface of this SubinterfacesTopSubinterfaces.
        :rtype: List[SubinterfacesTopSubinterfacesSubinterface]
        """
        return self._subinterface

    @subinterface.setter
    def subinterface(self, subinterface: List[SubinterfacesTopSubinterfacesSubinterface]):
        """Sets the subinterface of this SubinterfacesTopSubinterfaces.

        The list of subinterfaces (logical interfaces) associated with a physical interface  # noqa: E501

        :param subinterface: The subinterface of this SubinterfacesTopSubinterfaces.
        :type subinterface: List[SubinterfacesTopSubinterfacesSubinterface]
        """

        self._subinterface = subinterface
