# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.vlan_switched_config import VlanSwitchedConfig  # noqa: F401,E501
from swagger_server.models.vlan_switched_state import VlanSwitchedState  # noqa: F401,E501
from swagger_server import util


class SwitchedVlanSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: VlanSwitchedState=None, config: VlanSwitchedConfig=None):  # noqa: E501
        """SwitchedVlanSchema - a model defined in Swagger

        :param state: The state of this SwitchedVlanSchema.  # noqa: E501
        :type state: VlanSwitchedState
        :param config: The config of this SwitchedVlanSchema.  # noqa: E501
        :type config: VlanSwitchedConfig
        """
        self.swagger_types = {
            'state': VlanSwitchedState,
            'config': VlanSwitchedConfig
        }

        self.attribute_map = {
            'state': 'state',
            'config': 'config'
        }

        self._state = state
        self._config = config

    @classmethod
    def from_dict(cls, dikt) -> 'SwitchedVlanSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SwitchedVlanSchema of this SwitchedVlanSchema.  # noqa: E501
        :rtype: SwitchedVlanSchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> VlanSwitchedState:
        """Gets the state of this SwitchedVlanSchema.

        State variables for VLANs  # noqa: E501

        :return: The state of this SwitchedVlanSchema.
        :rtype: VlanSwitchedState
        """
        return self._state

    @state.setter
    def state(self, state: VlanSwitchedState):
        """Sets the state of this SwitchedVlanSchema.

        State variables for VLANs  # noqa: E501

        :param state: The state of this SwitchedVlanSchema.
        :type state: VlanSwitchedState
        """

        self._state = state

    @property
    def config(self) -> VlanSwitchedConfig:
        """Gets the config of this SwitchedVlanSchema.

        Configuration parameters for VLANs  # noqa: E501

        :return: The config of this SwitchedVlanSchema.
        :rtype: VlanSwitchedConfig
        """
        return self._config

    @config.setter
    def config(self, config: VlanSwitchedConfig):
        """Sets the config of this SwitchedVlanSchema.

        Configuration parameters for VLANs  # noqa: E501

        :param config: The config of this SwitchedVlanSchema.
        :type config: VlanSwitchedConfig
        """

        self._config = config
