# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.vlan_logical_single_tagged_range_config import VlanLogicalSingleTaggedRangeConfig  # noqa: F401,E501
from swagger_server import util


class VlanLogicalMatchTopMatchSingleTaggedRange(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: VlanLogicalSingleTaggedRangeConfig=None, config: VlanLogicalSingleTaggedRangeConfig=None):  # noqa: E501
        """VlanLogicalMatchTopMatchSingleTaggedRange - a model defined in Swagger

        :param state: The state of this VlanLogicalMatchTopMatchSingleTaggedRange.  # noqa: E501
        :type state: VlanLogicalSingleTaggedRangeConfig
        :param config: The config of this VlanLogicalMatchTopMatchSingleTaggedRange.  # noqa: E501
        :type config: VlanLogicalSingleTaggedRangeConfig
        """
        self.swagger_types = {
            'state': VlanLogicalSingleTaggedRangeConfig,
            'config': VlanLogicalSingleTaggedRangeConfig
        }

        self.attribute_map = {
            'state': 'state',
            'config': 'config'
        }

        self._state = state
        self._config = config

    @classmethod
    def from_dict(cls, dikt) -> 'VlanLogicalMatchTopMatchSingleTaggedRange':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VlanLogicalMatchTop_match_singleTaggedRange of this VlanLogicalMatchTopMatchSingleTaggedRange.  # noqa: E501
        :rtype: VlanLogicalMatchTopMatchSingleTaggedRange
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> VlanLogicalSingleTaggedRangeConfig:
        """Gets the state of this VlanLogicalMatchTopMatchSingleTaggedRange.

        State for matching single-tagged packets with a range of VLAN identifiers.  # noqa: E501

        :return: The state of this VlanLogicalMatchTopMatchSingleTaggedRange.
        :rtype: VlanLogicalSingleTaggedRangeConfig
        """
        return self._state

    @state.setter
    def state(self, state: VlanLogicalSingleTaggedRangeConfig):
        """Sets the state of this VlanLogicalMatchTopMatchSingleTaggedRange.

        State for matching single-tagged packets with a range of VLAN identifiers.  # noqa: E501

        :param state: The state of this VlanLogicalMatchTopMatchSingleTaggedRange.
        :type state: VlanLogicalSingleTaggedRangeConfig
        """

        self._state = state

    @property
    def config(self) -> VlanLogicalSingleTaggedRangeConfig:
        """Gets the config of this VlanLogicalMatchTopMatchSingleTaggedRange.

        Configuration for matching single-tagged packets with a range of VLAN identifiers.  # noqa: E501

        :return: The config of this VlanLogicalMatchTopMatchSingleTaggedRange.
        :rtype: VlanLogicalSingleTaggedRangeConfig
        """
        return self._config

    @config.setter
    def config(self, config: VlanLogicalSingleTaggedRangeConfig):
        """Sets the config of this VlanLogicalMatchTopMatchSingleTaggedRange.

        Configuration for matching single-tagged packets with a range of VLAN identifiers.  # noqa: E501

        :param config: The config of this VlanLogicalMatchTopMatchSingleTaggedRange.
        :type config: VlanLogicalSingleTaggedRangeConfig
        """

        self._config = config
