# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VlanLogicalSingleTaggedListConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, vlan_ids: List[str]=None):  # noqa: E501
        """VlanLogicalSingleTaggedListConfig - a model defined in Swagger

        :param vlan_ids: The vlan_ids of this VlanLogicalSingleTaggedListConfig.  # noqa: E501
        :type vlan_ids: List[str]
        """
        self.swagger_types = {
            'vlan_ids': List[str]
        }

        self.attribute_map = {
            'vlan_ids': 'vlanIds'
        }

        self._vlan_ids = vlan_ids

    @classmethod
    def from_dict(cls, dikt) -> 'VlanLogicalSingleTaggedListConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VlanLogicalSingleTaggedListConfig of this VlanLogicalSingleTaggedListConfig.  # noqa: E501
        :rtype: VlanLogicalSingleTaggedListConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vlan_ids(self) -> List[str]:
        """Gets the vlan_ids of this VlanLogicalSingleTaggedListConfig.


        :return: The vlan_ids of this VlanLogicalSingleTaggedListConfig.
        :rtype: List[str]
        """
        return self._vlan_ids

    @vlan_ids.setter
    def vlan_ids(self, vlan_ids: List[str]):
        """Sets the vlan_ids of this VlanLogicalSingleTaggedListConfig.


        :param vlan_ids: The vlan_ids of this VlanLogicalSingleTaggedListConfig.
        :type vlan_ids: List[str]
        """

        self._vlan_ids = vlan_ids
