# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.vlan_logical_match_top_match_double_tagged import VlanLogicalMatchTopMatchDoubleTagged  # noqa: F401,E501
from swagger_server.models.vlan_logical_match_top_match_double_tagged_inner_list import VlanLogicalMatchTopMatchDoubleTaggedInnerList  # noqa: F401,E501
from swagger_server.models.vlan_logical_match_top_match_double_tagged_inner_outer_range import VlanLogicalMatchTopMatchDoubleTaggedInnerOuterRange  # noqa: F401,E501
from swagger_server.models.vlan_logical_match_top_match_double_tagged_inner_range import VlanLogicalMatchTopMatchDoubleTaggedInnerRange  # noqa: F401,E501
from swagger_server.models.vlan_logical_match_top_match_double_tagged_outer_list import VlanLogicalMatchTopMatchDoubleTaggedOuterList  # noqa: F401,E501
from swagger_server.models.vlan_logical_match_top_match_double_tagged_outer_range import VlanLogicalMatchTopMatchDoubleTaggedOuterRange  # noqa: F401,E501
from swagger_server.models.vlan_logical_match_top_match_single_tagged import VlanLogicalMatchTopMatchSingleTagged  # noqa: F401,E501
from swagger_server.models.vlan_logical_match_top_match_single_tagged_list import VlanLogicalMatchTopMatchSingleTaggedList  # noqa: F401,E501
from swagger_server.models.vlan_logical_match_top_match_single_tagged_range import VlanLogicalMatchTopMatchSingleTaggedRange  # noqa: F401,E501
from swagger_server import util


class VlanLogicalMatchTopMatch(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, double_tagged_outer_list: VlanLogicalMatchTopMatchDoubleTaggedOuterList=None, double_tagged_outer_range: VlanLogicalMatchTopMatchDoubleTaggedOuterRange=None, single_tagged_range: VlanLogicalMatchTopMatchSingleTaggedRange=None, double_tagged: VlanLogicalMatchTopMatchDoubleTagged=None, single_tagged: VlanLogicalMatchTopMatchSingleTagged=None, double_tagged_inner_outer_range: VlanLogicalMatchTopMatchDoubleTaggedInnerOuterRange=None, double_tagged_inner_list: VlanLogicalMatchTopMatchDoubleTaggedInnerList=None, double_tagged_inner_range: VlanLogicalMatchTopMatchDoubleTaggedInnerRange=None, single_tagged_list: VlanLogicalMatchTopMatchSingleTaggedList=None):  # noqa: E501
        """VlanLogicalMatchTopMatch - a model defined in Swagger

        :param double_tagged_outer_list: The double_tagged_outer_list of this VlanLogicalMatchTopMatch.  # noqa: E501
        :type double_tagged_outer_list: VlanLogicalMatchTopMatchDoubleTaggedOuterList
        :param double_tagged_outer_range: The double_tagged_outer_range of this VlanLogicalMatchTopMatch.  # noqa: E501
        :type double_tagged_outer_range: VlanLogicalMatchTopMatchDoubleTaggedOuterRange
        :param single_tagged_range: The single_tagged_range of this VlanLogicalMatchTopMatch.  # noqa: E501
        :type single_tagged_range: VlanLogicalMatchTopMatchSingleTaggedRange
        :param double_tagged: The double_tagged of this VlanLogicalMatchTopMatch.  # noqa: E501
        :type double_tagged: VlanLogicalMatchTopMatchDoubleTagged
        :param single_tagged: The single_tagged of this VlanLogicalMatchTopMatch.  # noqa: E501
        :type single_tagged: VlanLogicalMatchTopMatchSingleTagged
        :param double_tagged_inner_outer_range: The double_tagged_inner_outer_range of this VlanLogicalMatchTopMatch.  # noqa: E501
        :type double_tagged_inner_outer_range: VlanLogicalMatchTopMatchDoubleTaggedInnerOuterRange
        :param double_tagged_inner_list: The double_tagged_inner_list of this VlanLogicalMatchTopMatch.  # noqa: E501
        :type double_tagged_inner_list: VlanLogicalMatchTopMatchDoubleTaggedInnerList
        :param double_tagged_inner_range: The double_tagged_inner_range of this VlanLogicalMatchTopMatch.  # noqa: E501
        :type double_tagged_inner_range: VlanLogicalMatchTopMatchDoubleTaggedInnerRange
        :param single_tagged_list: The single_tagged_list of this VlanLogicalMatchTopMatch.  # noqa: E501
        :type single_tagged_list: VlanLogicalMatchTopMatchSingleTaggedList
        """
        self.swagger_types = {
            'double_tagged_outer_list': VlanLogicalMatchTopMatchDoubleTaggedOuterList,
            'double_tagged_outer_range': VlanLogicalMatchTopMatchDoubleTaggedOuterRange,
            'single_tagged_range': VlanLogicalMatchTopMatchSingleTaggedRange,
            'double_tagged': VlanLogicalMatchTopMatchDoubleTagged,
            'single_tagged': VlanLogicalMatchTopMatchSingleTagged,
            'double_tagged_inner_outer_range': VlanLogicalMatchTopMatchDoubleTaggedInnerOuterRange,
            'double_tagged_inner_list': VlanLogicalMatchTopMatchDoubleTaggedInnerList,
            'double_tagged_inner_range': VlanLogicalMatchTopMatchDoubleTaggedInnerRange,
            'single_tagged_list': VlanLogicalMatchTopMatchSingleTaggedList
        }

        self.attribute_map = {
            'double_tagged_outer_list': 'doubleTaggedOuterList',
            'double_tagged_outer_range': 'doubleTaggedOuterRange',
            'single_tagged_range': 'singleTaggedRange',
            'double_tagged': 'doubleTagged',
            'single_tagged': 'singleTagged',
            'double_tagged_inner_outer_range': 'doubleTaggedInnerOuterRange',
            'double_tagged_inner_list': 'doubleTaggedInnerList',
            'double_tagged_inner_range': 'doubleTaggedInnerRange',
            'single_tagged_list': 'singleTaggedList'
        }

        self._double_tagged_outer_list = double_tagged_outer_list
        self._double_tagged_outer_range = double_tagged_outer_range
        self._single_tagged_range = single_tagged_range
        self._double_tagged = double_tagged
        self._single_tagged = single_tagged
        self._double_tagged_inner_outer_range = double_tagged_inner_outer_range
        self._double_tagged_inner_list = double_tagged_inner_list
        self._double_tagged_inner_range = double_tagged_inner_range
        self._single_tagged_list = single_tagged_list

    @classmethod
    def from_dict(cls, dikt) -> 'VlanLogicalMatchTopMatch':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VlanLogicalMatchTop_match of this VlanLogicalMatchTopMatch.  # noqa: E501
        :rtype: VlanLogicalMatchTopMatch
        """
        return util.deserialize_model(dikt, cls)

    @property
    def double_tagged_outer_list(self) -> VlanLogicalMatchTopMatchDoubleTaggedOuterList:
        """Gets the double_tagged_outer_list of this VlanLogicalMatchTopMatch.


        :return: The double_tagged_outer_list of this VlanLogicalMatchTopMatch.
        :rtype: VlanLogicalMatchTopMatchDoubleTaggedOuterList
        """
        return self._double_tagged_outer_list

    @double_tagged_outer_list.setter
    def double_tagged_outer_list(self, double_tagged_outer_list: VlanLogicalMatchTopMatchDoubleTaggedOuterList):
        """Sets the double_tagged_outer_list of this VlanLogicalMatchTopMatch.


        :param double_tagged_outer_list: The double_tagged_outer_list of this VlanLogicalMatchTopMatch.
        :type double_tagged_outer_list: VlanLogicalMatchTopMatchDoubleTaggedOuterList
        """

        self._double_tagged_outer_list = double_tagged_outer_list

    @property
    def double_tagged_outer_range(self) -> VlanLogicalMatchTopMatchDoubleTaggedOuterRange:
        """Gets the double_tagged_outer_range of this VlanLogicalMatchTopMatch.


        :return: The double_tagged_outer_range of this VlanLogicalMatchTopMatch.
        :rtype: VlanLogicalMatchTopMatchDoubleTaggedOuterRange
        """
        return self._double_tagged_outer_range

    @double_tagged_outer_range.setter
    def double_tagged_outer_range(self, double_tagged_outer_range: VlanLogicalMatchTopMatchDoubleTaggedOuterRange):
        """Sets the double_tagged_outer_range of this VlanLogicalMatchTopMatch.


        :param double_tagged_outer_range: The double_tagged_outer_range of this VlanLogicalMatchTopMatch.
        :type double_tagged_outer_range: VlanLogicalMatchTopMatchDoubleTaggedOuterRange
        """

        self._double_tagged_outer_range = double_tagged_outer_range

    @property
    def single_tagged_range(self) -> VlanLogicalMatchTopMatchSingleTaggedRange:
        """Gets the single_tagged_range of this VlanLogicalMatchTopMatch.


        :return: The single_tagged_range of this VlanLogicalMatchTopMatch.
        :rtype: VlanLogicalMatchTopMatchSingleTaggedRange
        """
        return self._single_tagged_range

    @single_tagged_range.setter
    def single_tagged_range(self, single_tagged_range: VlanLogicalMatchTopMatchSingleTaggedRange):
        """Sets the single_tagged_range of this VlanLogicalMatchTopMatch.


        :param single_tagged_range: The single_tagged_range of this VlanLogicalMatchTopMatch.
        :type single_tagged_range: VlanLogicalMatchTopMatchSingleTaggedRange
        """

        self._single_tagged_range = single_tagged_range

    @property
    def double_tagged(self) -> VlanLogicalMatchTopMatchDoubleTagged:
        """Gets the double_tagged of this VlanLogicalMatchTopMatch.


        :return: The double_tagged of this VlanLogicalMatchTopMatch.
        :rtype: VlanLogicalMatchTopMatchDoubleTagged
        """
        return self._double_tagged

    @double_tagged.setter
    def double_tagged(self, double_tagged: VlanLogicalMatchTopMatchDoubleTagged):
        """Sets the double_tagged of this VlanLogicalMatchTopMatch.


        :param double_tagged: The double_tagged of this VlanLogicalMatchTopMatch.
        :type double_tagged: VlanLogicalMatchTopMatchDoubleTagged
        """

        self._double_tagged = double_tagged

    @property
    def single_tagged(self) -> VlanLogicalMatchTopMatchSingleTagged:
        """Gets the single_tagged of this VlanLogicalMatchTopMatch.


        :return: The single_tagged of this VlanLogicalMatchTopMatch.
        :rtype: VlanLogicalMatchTopMatchSingleTagged
        """
        return self._single_tagged

    @single_tagged.setter
    def single_tagged(self, single_tagged: VlanLogicalMatchTopMatchSingleTagged):
        """Sets the single_tagged of this VlanLogicalMatchTopMatch.


        :param single_tagged: The single_tagged of this VlanLogicalMatchTopMatch.
        :type single_tagged: VlanLogicalMatchTopMatchSingleTagged
        """

        self._single_tagged = single_tagged

    @property
    def double_tagged_inner_outer_range(self) -> VlanLogicalMatchTopMatchDoubleTaggedInnerOuterRange:
        """Gets the double_tagged_inner_outer_range of this VlanLogicalMatchTopMatch.


        :return: The double_tagged_inner_outer_range of this VlanLogicalMatchTopMatch.
        :rtype: VlanLogicalMatchTopMatchDoubleTaggedInnerOuterRange
        """
        return self._double_tagged_inner_outer_range

    @double_tagged_inner_outer_range.setter
    def double_tagged_inner_outer_range(self, double_tagged_inner_outer_range: VlanLogicalMatchTopMatchDoubleTaggedInnerOuterRange):
        """Sets the double_tagged_inner_outer_range of this VlanLogicalMatchTopMatch.


        :param double_tagged_inner_outer_range: The double_tagged_inner_outer_range of this VlanLogicalMatchTopMatch.
        :type double_tagged_inner_outer_range: VlanLogicalMatchTopMatchDoubleTaggedInnerOuterRange
        """

        self._double_tagged_inner_outer_range = double_tagged_inner_outer_range

    @property
    def double_tagged_inner_list(self) -> VlanLogicalMatchTopMatchDoubleTaggedInnerList:
        """Gets the double_tagged_inner_list of this VlanLogicalMatchTopMatch.


        :return: The double_tagged_inner_list of this VlanLogicalMatchTopMatch.
        :rtype: VlanLogicalMatchTopMatchDoubleTaggedInnerList
        """
        return self._double_tagged_inner_list

    @double_tagged_inner_list.setter
    def double_tagged_inner_list(self, double_tagged_inner_list: VlanLogicalMatchTopMatchDoubleTaggedInnerList):
        """Sets the double_tagged_inner_list of this VlanLogicalMatchTopMatch.


        :param double_tagged_inner_list: The double_tagged_inner_list of this VlanLogicalMatchTopMatch.
        :type double_tagged_inner_list: VlanLogicalMatchTopMatchDoubleTaggedInnerList
        """

        self._double_tagged_inner_list = double_tagged_inner_list

    @property
    def double_tagged_inner_range(self) -> VlanLogicalMatchTopMatchDoubleTaggedInnerRange:
        """Gets the double_tagged_inner_range of this VlanLogicalMatchTopMatch.


        :return: The double_tagged_inner_range of this VlanLogicalMatchTopMatch.
        :rtype: VlanLogicalMatchTopMatchDoubleTaggedInnerRange
        """
        return self._double_tagged_inner_range

    @double_tagged_inner_range.setter
    def double_tagged_inner_range(self, double_tagged_inner_range: VlanLogicalMatchTopMatchDoubleTaggedInnerRange):
        """Sets the double_tagged_inner_range of this VlanLogicalMatchTopMatch.


        :param double_tagged_inner_range: The double_tagged_inner_range of this VlanLogicalMatchTopMatch.
        :type double_tagged_inner_range: VlanLogicalMatchTopMatchDoubleTaggedInnerRange
        """

        self._double_tagged_inner_range = double_tagged_inner_range

    @property
    def single_tagged_list(self) -> VlanLogicalMatchTopMatchSingleTaggedList:
        """Gets the single_tagged_list of this VlanLogicalMatchTopMatch.


        :return: The single_tagged_list of this VlanLogicalMatchTopMatch.
        :rtype: VlanLogicalMatchTopMatchSingleTaggedList
        """
        return self._single_tagged_list

    @single_tagged_list.setter
    def single_tagged_list(self, single_tagged_list: VlanLogicalMatchTopMatchSingleTaggedList):
        """Sets the single_tagged_list of this VlanLogicalMatchTopMatch.


        :param single_tagged_list: The single_tagged_list of this VlanLogicalMatchTopMatch.
        :type single_tagged_list: VlanLogicalMatchTopMatchSingleTaggedList
        """

        self._single_tagged_list = single_tagged_list
