# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VlanLogicalDoubleTaggedInnerOuterRangeConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, inner_low_vlan_id: str=None, inner_high_vlan_id: str=None, outer_low_vlan_id: str=None, outer_high_vlan_id: str=None):  # noqa: E501
        """VlanLogicalDoubleTaggedInnerOuterRangeConfig - a model defined in Swagger

        :param inner_low_vlan_id: The inner_low_vlan_id of this VlanLogicalDoubleTaggedInnerOuterRangeConfig.  # noqa: E501
        :type inner_low_vlan_id: str
        :param inner_high_vlan_id: The inner_high_vlan_id of this VlanLogicalDoubleTaggedInnerOuterRangeConfig.  # noqa: E501
        :type inner_high_vlan_id: str
        :param outer_low_vlan_id: The outer_low_vlan_id of this VlanLogicalDoubleTaggedInnerOuterRangeConfig.  # noqa: E501
        :type outer_low_vlan_id: str
        :param outer_high_vlan_id: The outer_high_vlan_id of this VlanLogicalDoubleTaggedInnerOuterRangeConfig.  # noqa: E501
        :type outer_high_vlan_id: str
        """
        self.swagger_types = {
            'inner_low_vlan_id': str,
            'inner_high_vlan_id': str,
            'outer_low_vlan_id': str,
            'outer_high_vlan_id': str
        }

        self.attribute_map = {
            'inner_low_vlan_id': 'innerLowVlanId',
            'inner_high_vlan_id': 'innerHighVlanId',
            'outer_low_vlan_id': 'outerLowVlanId',
            'outer_high_vlan_id': 'outerHighVlanId'
        }

        self._inner_low_vlan_id = inner_low_vlan_id
        self._inner_high_vlan_id = inner_high_vlan_id
        self._outer_low_vlan_id = outer_low_vlan_id
        self._outer_high_vlan_id = outer_high_vlan_id

    @classmethod
    def from_dict(cls, dikt) -> 'VlanLogicalDoubleTaggedInnerOuterRangeConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VlanLogicalDoubleTaggedInnerOuterRangeConfig of this VlanLogicalDoubleTaggedInnerOuterRangeConfig.  # noqa: E501
        :rtype: VlanLogicalDoubleTaggedInnerOuterRangeConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def inner_low_vlan_id(self) -> str:
        """Gets the inner_low_vlan_id of this VlanLogicalDoubleTaggedInnerOuterRangeConfig.

        The low-value inner VLAN identifier in a range for double-tagged packets. The range is matched inclusively.  # noqa: E501

        :return: The inner_low_vlan_id of this VlanLogicalDoubleTaggedInnerOuterRangeConfig.
        :rtype: str
        """
        return self._inner_low_vlan_id

    @inner_low_vlan_id.setter
    def inner_low_vlan_id(self, inner_low_vlan_id: str):
        """Sets the inner_low_vlan_id of this VlanLogicalDoubleTaggedInnerOuterRangeConfig.

        The low-value inner VLAN identifier in a range for double-tagged packets. The range is matched inclusively.  # noqa: E501

        :param inner_low_vlan_id: The inner_low_vlan_id of this VlanLogicalDoubleTaggedInnerOuterRangeConfig.
        :type inner_low_vlan_id: str
        """

        self._inner_low_vlan_id = inner_low_vlan_id

    @property
    def inner_high_vlan_id(self) -> str:
        """Gets the inner_high_vlan_id of this VlanLogicalDoubleTaggedInnerOuterRangeConfig.

        The high-value inner VLAN identifier in a range for double-tagged packets. The range is matched inclusively.  # noqa: E501

        :return: The inner_high_vlan_id of this VlanLogicalDoubleTaggedInnerOuterRangeConfig.
        :rtype: str
        """
        return self._inner_high_vlan_id

    @inner_high_vlan_id.setter
    def inner_high_vlan_id(self, inner_high_vlan_id: str):
        """Sets the inner_high_vlan_id of this VlanLogicalDoubleTaggedInnerOuterRangeConfig.

        The high-value inner VLAN identifier in a range for double-tagged packets. The range is matched inclusively.  # noqa: E501

        :param inner_high_vlan_id: The inner_high_vlan_id of this VlanLogicalDoubleTaggedInnerOuterRangeConfig.
        :type inner_high_vlan_id: str
        """

        self._inner_high_vlan_id = inner_high_vlan_id

    @property
    def outer_low_vlan_id(self) -> str:
        """Gets the outer_low_vlan_id of this VlanLogicalDoubleTaggedInnerOuterRangeConfig.

        The low-value outer VLAN identifier in a range for double-tagged packets. The range is matched inclusively.  # noqa: E501

        :return: The outer_low_vlan_id of this VlanLogicalDoubleTaggedInnerOuterRangeConfig.
        :rtype: str
        """
        return self._outer_low_vlan_id

    @outer_low_vlan_id.setter
    def outer_low_vlan_id(self, outer_low_vlan_id: str):
        """Sets the outer_low_vlan_id of this VlanLogicalDoubleTaggedInnerOuterRangeConfig.

        The low-value outer VLAN identifier in a range for double-tagged packets. The range is matched inclusively.  # noqa: E501

        :param outer_low_vlan_id: The outer_low_vlan_id of this VlanLogicalDoubleTaggedInnerOuterRangeConfig.
        :type outer_low_vlan_id: str
        """

        self._outer_low_vlan_id = outer_low_vlan_id

    @property
    def outer_high_vlan_id(self) -> str:
        """Gets the outer_high_vlan_id of this VlanLogicalDoubleTaggedInnerOuterRangeConfig.

        The high-value outer VLAN identifier for double-tagged packets. The range is matched inclusively.  # noqa: E501

        :return: The outer_high_vlan_id of this VlanLogicalDoubleTaggedInnerOuterRangeConfig.
        :rtype: str
        """
        return self._outer_high_vlan_id

    @outer_high_vlan_id.setter
    def outer_high_vlan_id(self, outer_high_vlan_id: str):
        """Sets the outer_high_vlan_id of this VlanLogicalDoubleTaggedInnerOuterRangeConfig.

        The high-value outer VLAN identifier for double-tagged packets. The range is matched inclusively.  # noqa: E501

        :param outer_high_vlan_id: The outer_high_vlan_id of this VlanLogicalDoubleTaggedInnerOuterRangeConfig.
        :type outer_high_vlan_id: str
        """

        self._outer_high_vlan_id = outer_high_vlan_id
