# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VlanLogicalDoubleTaggedOuterListConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, outer_vlan_ids: List[str]=None, inner_vlan_id: str=None):  # noqa: E501
        """VlanLogicalDoubleTaggedOuterListConfig - a model defined in Swagger

        :param outer_vlan_ids: The outer_vlan_ids of this VlanLogicalDoubleTaggedOuterListConfig.  # noqa: E501
        :type outer_vlan_ids: List[str]
        :param inner_vlan_id: The inner_vlan_id of this VlanLogicalDoubleTaggedOuterListConfig.  # noqa: E501
        :type inner_vlan_id: str
        """
        self.swagger_types = {
            'outer_vlan_ids': List[str],
            'inner_vlan_id': str
        }

        self.attribute_map = {
            'outer_vlan_ids': 'outerVlanIds',
            'inner_vlan_id': 'innerVlanId'
        }

        self._outer_vlan_ids = outer_vlan_ids
        self._inner_vlan_id = inner_vlan_id

    @classmethod
    def from_dict(cls, dikt) -> 'VlanLogicalDoubleTaggedOuterListConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VlanLogicalDoubleTaggedOuterListConfig of this VlanLogicalDoubleTaggedOuterListConfig.  # noqa: E501
        :rtype: VlanLogicalDoubleTaggedOuterListConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def outer_vlan_ids(self) -> List[str]:
        """Gets the outer_vlan_ids of this VlanLogicalDoubleTaggedOuterListConfig.


        :return: The outer_vlan_ids of this VlanLogicalDoubleTaggedOuterListConfig.
        :rtype: List[str]
        """
        return self._outer_vlan_ids

    @outer_vlan_ids.setter
    def outer_vlan_ids(self, outer_vlan_ids: List[str]):
        """Sets the outer_vlan_ids of this VlanLogicalDoubleTaggedOuterListConfig.


        :param outer_vlan_ids: The outer_vlan_ids of this VlanLogicalDoubleTaggedOuterListConfig.
        :type outer_vlan_ids: List[str]
        """

        self._outer_vlan_ids = outer_vlan_ids

    @property
    def inner_vlan_id(self) -> str:
        """Gets the inner_vlan_id of this VlanLogicalDoubleTaggedOuterListConfig.

        Inner VLAN identifier for double-tagged packets.  # noqa: E501

        :return: The inner_vlan_id of this VlanLogicalDoubleTaggedOuterListConfig.
        :rtype: str
        """
        return self._inner_vlan_id

    @inner_vlan_id.setter
    def inner_vlan_id(self, inner_vlan_id: str):
        """Sets the inner_vlan_id of this VlanLogicalDoubleTaggedOuterListConfig.

        Inner VLAN identifier for double-tagged packets.  # noqa: E501

        :param inner_vlan_id: The inner_vlan_id of this VlanLogicalDoubleTaggedOuterListConfig.
        :type inner_vlan_id: str
        """

        self._inner_vlan_id = inner_vlan_id
