# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VlanLogicalSingleTaggedConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, vlan_id: str=None):  # noqa: E501
        """VlanLogicalSingleTaggedConfig - a model defined in Swagger

        :param vlan_id: The vlan_id of this VlanLogicalSingleTaggedConfig.  # noqa: E501
        :type vlan_id: str
        """
        self.swagger_types = {
            'vlan_id': str
        }

        self.attribute_map = {
            'vlan_id': 'vlanId'
        }

        self._vlan_id = vlan_id

    @classmethod
    def from_dict(cls, dikt) -> 'VlanLogicalSingleTaggedConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VlanLogicalSingleTaggedConfig of this VlanLogicalSingleTaggedConfig.  # noqa: E501
        :rtype: VlanLogicalSingleTaggedConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vlan_id(self) -> str:
        """Gets the vlan_id of this VlanLogicalSingleTaggedConfig.

        VLAN identifier for single-tagged packets.  # noqa: E501

        :return: The vlan_id of this VlanLogicalSingleTaggedConfig.
        :rtype: str
        """
        return self._vlan_id

    @vlan_id.setter
    def vlan_id(self, vlan_id: str):
        """Sets the vlan_id of this VlanLogicalSingleTaggedConfig.

        VLAN identifier for single-tagged packets.  # noqa: E501

        :param vlan_id: The vlan_id of this VlanLogicalSingleTaggedConfig.
        :type vlan_id: str
        """

        self._vlan_id = vlan_id
