# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.vlan_logical_single_tagged_config import VlanLogicalSingleTaggedConfig  # noqa: F401,E501
from swagger_server import util


class VlanLogicalMatchTopMatchSingleTagged(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: VlanLogicalSingleTaggedConfig=None, config: VlanLogicalSingleTaggedConfig=None):  # noqa: E501
        """VlanLogicalMatchTopMatchSingleTagged - a model defined in Swagger

        :param state: The state of this VlanLogicalMatchTopMatchSingleTagged.  # noqa: E501
        :type state: VlanLogicalSingleTaggedConfig
        :param config: The config of this VlanLogicalMatchTopMatchSingleTagged.  # noqa: E501
        :type config: VlanLogicalSingleTaggedConfig
        """
        self.swagger_types = {
            'state': VlanLogicalSingleTaggedConfig,
            'config': VlanLogicalSingleTaggedConfig
        }

        self.attribute_map = {
            'state': 'state',
            'config': 'config'
        }

        self._state = state
        self._config = config

    @classmethod
    def from_dict(cls, dikt) -> 'VlanLogicalMatchTopMatchSingleTagged':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VlanLogicalMatchTop_match_singleTagged of this VlanLogicalMatchTopMatchSingleTagged.  # noqa: E501
        :rtype: VlanLogicalMatchTopMatchSingleTagged
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> VlanLogicalSingleTaggedConfig:
        """Gets the state of this VlanLogicalMatchTopMatchSingleTagged.

        State for matching single-tagged packets with an exact VLAN identifier.  # noqa: E501

        :return: The state of this VlanLogicalMatchTopMatchSingleTagged.
        :rtype: VlanLogicalSingleTaggedConfig
        """
        return self._state

    @state.setter
    def state(self, state: VlanLogicalSingleTaggedConfig):
        """Sets the state of this VlanLogicalMatchTopMatchSingleTagged.

        State for matching single-tagged packets with an exact VLAN identifier.  # noqa: E501

        :param state: The state of this VlanLogicalMatchTopMatchSingleTagged.
        :type state: VlanLogicalSingleTaggedConfig
        """

        self._state = state

    @property
    def config(self) -> VlanLogicalSingleTaggedConfig:
        """Gets the config of this VlanLogicalMatchTopMatchSingleTagged.

        Configuration for matching single-tagged packets with an exact VLAN identifier.  # noqa: E501

        :return: The config of this VlanLogicalMatchTopMatchSingleTagged.
        :rtype: VlanLogicalSingleTaggedConfig
        """
        return self._config

    @config.setter
    def config(self, config: VlanLogicalSingleTaggedConfig):
        """Sets the config of this VlanLogicalMatchTopMatchSingleTagged.

        Configuration for matching single-tagged packets with an exact VLAN identifier.  # noqa: E501

        :param config: The config of this VlanLogicalMatchTopMatchSingleTagged.
        :type config: VlanLogicalSingleTaggedConfig
        """

        self._config = config
