# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VlanRoutedConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, vlan: str=None):  # noqa: E501
        """VlanRoutedConfig - a model defined in Swagger

        :param vlan: The vlan of this VlanRoutedConfig.  # noqa: E501
        :type vlan: str
        """
        self.swagger_types = {
            'vlan': str
        }

        self.attribute_map = {
            'vlan': 'vlan'
        }

        self._vlan = vlan

    @classmethod
    def from_dict(cls, dikt) -> 'VlanRoutedConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VlanRoutedConfig of this VlanRoutedConfig.  # noqa: E501
        :rtype: VlanRoutedConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vlan(self) -> str:
        """Gets the vlan of this VlanRoutedConfig.

        References the VLAN for which this IP interface provides routing services -- similar to a switch virtual interface (SVI), or integrated routing and bridging interface (IRB) in some implementations.  # noqa: E501

        :return: The vlan of this VlanRoutedConfig.
        :rtype: str
        """
        return self._vlan

    @vlan.setter
    def vlan(self, vlan: str):
        """Sets the vlan of this VlanRoutedConfig.

        References the VLAN for which this IP interface provides routing services -- similar to a switch virtual interface (SVI), or integrated routing and bridging interface (IRB) in some implementations.  # noqa: E501

        :param vlan: The vlan of this VlanRoutedConfig.
        :type vlan: str
        """

        self._vlan = vlan
