# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VlanLogicalTop(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, vlan: object=None):  # noqa: E501
        """VlanLogicalTop - a model defined in Swagger

        :param vlan: The vlan of this VlanLogicalTop.  # noqa: E501
        :type vlan: object
        """
        self.swagger_types = {
            'vlan': object
        }

        self.attribute_map = {
            'vlan': 'vlan'
        }

        self._vlan = vlan

    @classmethod
    def from_dict(cls, dikt) -> 'VlanLogicalTop':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VlanLogicalTop of this VlanLogicalTop.  # noqa: E501
        :rtype: VlanLogicalTop
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vlan(self) -> object:
        """Gets the vlan of this VlanLogicalTop.

        Enclosing container for VLAN interface-specific data on subinterfaces  # noqa: E501

        :return: The vlan of this VlanLogicalTop.
        :rtype: object
        """
        return self._vlan

    @vlan.setter
    def vlan(self, vlan: object):
        """Sets the vlan of this VlanLogicalTop.

        Enclosing container for VLAN interface-specific data on subinterfaces  # noqa: E501

        :param vlan: The vlan of this VlanLogicalTop.
        :type vlan: object
        """

        self._vlan = vlan
