# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.vlan_logical_double_tagged_outer_range_config import VlanLogicalDoubleTaggedOuterRangeConfig  # noqa: F401,E501
from swagger_server import util


class VlanLogicalMatchTopMatchDoubleTaggedOuterRange(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: VlanLogicalDoubleTaggedOuterRangeConfig=None, config: VlanLogicalDoubleTaggedOuterRangeConfig=None):  # noqa: E501
        """VlanLogicalMatchTopMatchDoubleTaggedOuterRange - a model defined in Swagger

        :param state: The state of this VlanLogicalMatchTopMatchDoubleTaggedOuterRange.  # noqa: E501
        :type state: VlanLogicalDoubleTaggedOuterRangeConfig
        :param config: The config of this VlanLogicalMatchTopMatchDoubleTaggedOuterRange.  # noqa: E501
        :type config: VlanLogicalDoubleTaggedOuterRangeConfig
        """
        self.swagger_types = {
            'state': VlanLogicalDoubleTaggedOuterRangeConfig,
            'config': VlanLogicalDoubleTaggedOuterRangeConfig
        }

        self.attribute_map = {
            'state': 'state',
            'config': 'config'
        }

        self._state = state
        self._config = config

    @classmethod
    def from_dict(cls, dikt) -> 'VlanLogicalMatchTopMatchDoubleTaggedOuterRange':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VlanLogicalMatchTop_match_doubleTaggedOuterRange of this VlanLogicalMatchTopMatchDoubleTaggedOuterRange.  # noqa: E501
        :rtype: VlanLogicalMatchTopMatchDoubleTaggedOuterRange
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> VlanLogicalDoubleTaggedOuterRangeConfig:
        """Gets the state of this VlanLogicalMatchTopMatchDoubleTaggedOuterRange.

        State for matching double-tagged packets against an inner exact and an outer range of VLAN identifiers.  # noqa: E501

        :return: The state of this VlanLogicalMatchTopMatchDoubleTaggedOuterRange.
        :rtype: VlanLogicalDoubleTaggedOuterRangeConfig
        """
        return self._state

    @state.setter
    def state(self, state: VlanLogicalDoubleTaggedOuterRangeConfig):
        """Sets the state of this VlanLogicalMatchTopMatchDoubleTaggedOuterRange.

        State for matching double-tagged packets against an inner exact and an outer range of VLAN identifiers.  # noqa: E501

        :param state: The state of this VlanLogicalMatchTopMatchDoubleTaggedOuterRange.
        :type state: VlanLogicalDoubleTaggedOuterRangeConfig
        """

        self._state = state

    @property
    def config(self) -> VlanLogicalDoubleTaggedOuterRangeConfig:
        """Gets the config of this VlanLogicalMatchTopMatchDoubleTaggedOuterRange.

        Configuration for matching double-tagged packets against an inner exact and an outer range of VLAN identifiers.  # noqa: E501

        :return: The config of this VlanLogicalMatchTopMatchDoubleTaggedOuterRange.
        :rtype: VlanLogicalDoubleTaggedOuterRangeConfig
        """
        return self._config

    @config.setter
    def config(self, config: VlanLogicalDoubleTaggedOuterRangeConfig):
        """Sets the config of this VlanLogicalMatchTopMatchDoubleTaggedOuterRange.

        Configuration for matching double-tagged packets against an inner exact and an outer range of VLAN identifiers.  # noqa: E501

        :param config: The config of this VlanLogicalMatchTopMatchDoubleTaggedOuterRange.
        :type config: VlanLogicalDoubleTaggedOuterRangeConfig
        """

        self._config = config
