# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VlanLogicalDoubleTaggedOuterRangeConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, inner_vlan_id: str=None, outer_low_vlan_id: str=None, outer_high_vlan_id: str=None):  # noqa: E501
        """VlanLogicalDoubleTaggedOuterRangeConfig - a model defined in Swagger

        :param inner_vlan_id: The inner_vlan_id of this VlanLogicalDoubleTaggedOuterRangeConfig.  # noqa: E501
        :type inner_vlan_id: str
        :param outer_low_vlan_id: The outer_low_vlan_id of this VlanLogicalDoubleTaggedOuterRangeConfig.  # noqa: E501
        :type outer_low_vlan_id: str
        :param outer_high_vlan_id: The outer_high_vlan_id of this VlanLogicalDoubleTaggedOuterRangeConfig.  # noqa: E501
        :type outer_high_vlan_id: str
        """
        self.swagger_types = {
            'inner_vlan_id': str,
            'outer_low_vlan_id': str,
            'outer_high_vlan_id': str
        }

        self.attribute_map = {
            'inner_vlan_id': 'innerVlanId',
            'outer_low_vlan_id': 'outerLowVlanId',
            'outer_high_vlan_id': 'outerHighVlanId'
        }

        self._inner_vlan_id = inner_vlan_id
        self._outer_low_vlan_id = outer_low_vlan_id
        self._outer_high_vlan_id = outer_high_vlan_id

    @classmethod
    def from_dict(cls, dikt) -> 'VlanLogicalDoubleTaggedOuterRangeConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VlanLogicalDoubleTaggedOuterRangeConfig of this VlanLogicalDoubleTaggedOuterRangeConfig.  # noqa: E501
        :rtype: VlanLogicalDoubleTaggedOuterRangeConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def inner_vlan_id(self) -> str:
        """Gets the inner_vlan_id of this VlanLogicalDoubleTaggedOuterRangeConfig.

        Inner VLAN identifier for double-tagged packets.  # noqa: E501

        :return: The inner_vlan_id of this VlanLogicalDoubleTaggedOuterRangeConfig.
        :rtype: str
        """
        return self._inner_vlan_id

    @inner_vlan_id.setter
    def inner_vlan_id(self, inner_vlan_id: str):
        """Sets the inner_vlan_id of this VlanLogicalDoubleTaggedOuterRangeConfig.

        Inner VLAN identifier for double-tagged packets.  # noqa: E501

        :param inner_vlan_id: The inner_vlan_id of this VlanLogicalDoubleTaggedOuterRangeConfig.
        :type inner_vlan_id: str
        """

        self._inner_vlan_id = inner_vlan_id

    @property
    def outer_low_vlan_id(self) -> str:
        """Gets the outer_low_vlan_id of this VlanLogicalDoubleTaggedOuterRangeConfig.

        The low-value outer VLAN identifier for double-tagged packets. The range is matched inclusively.  # noqa: E501

        :return: The outer_low_vlan_id of this VlanLogicalDoubleTaggedOuterRangeConfig.
        :rtype: str
        """
        return self._outer_low_vlan_id

    @outer_low_vlan_id.setter
    def outer_low_vlan_id(self, outer_low_vlan_id: str):
        """Sets the outer_low_vlan_id of this VlanLogicalDoubleTaggedOuterRangeConfig.

        The low-value outer VLAN identifier for double-tagged packets. The range is matched inclusively.  # noqa: E501

        :param outer_low_vlan_id: The outer_low_vlan_id of this VlanLogicalDoubleTaggedOuterRangeConfig.
        :type outer_low_vlan_id: str
        """

        self._outer_low_vlan_id = outer_low_vlan_id

    @property
    def outer_high_vlan_id(self) -> str:
        """Gets the outer_high_vlan_id of this VlanLogicalDoubleTaggedOuterRangeConfig.

        The high-value outer VLAN identifier for double-tagged packets. The range is matched inclusively.  # noqa: E501

        :return: The outer_high_vlan_id of this VlanLogicalDoubleTaggedOuterRangeConfig.
        :rtype: str
        """
        return self._outer_high_vlan_id

    @outer_high_vlan_id.setter
    def outer_high_vlan_id(self, outer_high_vlan_id: str):
        """Sets the outer_high_vlan_id of this VlanLogicalDoubleTaggedOuterRangeConfig.

        The high-value outer VLAN identifier for double-tagged packets. The range is matched inclusively.  # noqa: E501

        :param outer_high_vlan_id: The outer_high_vlan_id of this VlanLogicalDoubleTaggedOuterRangeConfig.
        :type outer_high_vlan_id: str
        """

        self._outer_high_vlan_id = outer_high_vlan_id
