# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VlanTopVlans(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, vlan: List[object]=None):  # noqa: E501
        """VlanTopVlans - a model defined in Swagger

        :param vlan: The vlan of this VlanTopVlans.  # noqa: E501
        :type vlan: List[object]
        """
        self.swagger_types = {
            'vlan': List[object]
        }

        self.attribute_map = {
            'vlan': 'vlan'
        }

        self._vlan = vlan

    @classmethod
    def from_dict(cls, dikt) -> 'VlanTopVlans':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VlanTop_vlans of this VlanTopVlans.  # noqa: E501
        :rtype: VlanTopVlans
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vlan(self) -> List[object]:
        """Gets the vlan of this VlanTopVlans.

        Configured VLANs keyed by id  # noqa: E501

        :return: The vlan of this VlanTopVlans.
        :rtype: List[object]
        """
        return self._vlan

    @vlan.setter
    def vlan(self, vlan: List[object]):
        """Sets the vlan of this VlanTopVlans.

        Configured VLANs keyed by id  # noqa: E501

        :param vlan: The vlan of this VlanTopVlans.
        :type vlan: List[object]
        """

        self._vlan = vlan
