# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VlanLogicalDoubleTaggedInnerListConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, outer_vlan_id: str=None, inner_vlan_ids: List[str]=None):  # noqa: E501
        """VlanLogicalDoubleTaggedInnerListConfig - a model defined in Swagger

        :param outer_vlan_id: The outer_vlan_id of this VlanLogicalDoubleTaggedInnerListConfig.  # noqa: E501
        :type outer_vlan_id: str
        :param inner_vlan_ids: The inner_vlan_ids of this VlanLogicalDoubleTaggedInnerListConfig.  # noqa: E501
        :type inner_vlan_ids: List[str]
        """
        self.swagger_types = {
            'outer_vlan_id': str,
            'inner_vlan_ids': List[str]
        }

        self.attribute_map = {
            'outer_vlan_id': 'outerVlanId',
            'inner_vlan_ids': 'innerVlanIds'
        }

        self._outer_vlan_id = outer_vlan_id
        self._inner_vlan_ids = inner_vlan_ids

    @classmethod
    def from_dict(cls, dikt) -> 'VlanLogicalDoubleTaggedInnerListConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VlanLogicalDoubleTaggedInnerListConfig of this VlanLogicalDoubleTaggedInnerListConfig.  # noqa: E501
        :rtype: VlanLogicalDoubleTaggedInnerListConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def outer_vlan_id(self) -> str:
        """Gets the outer_vlan_id of this VlanLogicalDoubleTaggedInnerListConfig.

        Outer VLAN identifier for double-tagged packets.  # noqa: E501

        :return: The outer_vlan_id of this VlanLogicalDoubleTaggedInnerListConfig.
        :rtype: str
        """
        return self._outer_vlan_id

    @outer_vlan_id.setter
    def outer_vlan_id(self, outer_vlan_id: str):
        """Sets the outer_vlan_id of this VlanLogicalDoubleTaggedInnerListConfig.

        Outer VLAN identifier for double-tagged packets.  # noqa: E501

        :param outer_vlan_id: The outer_vlan_id of this VlanLogicalDoubleTaggedInnerListConfig.
        :type outer_vlan_id: str
        """

        self._outer_vlan_id = outer_vlan_id

    @property
    def inner_vlan_ids(self) -> List[str]:
        """Gets the inner_vlan_ids of this VlanLogicalDoubleTaggedInnerListConfig.


        :return: The inner_vlan_ids of this VlanLogicalDoubleTaggedInnerListConfig.
        :rtype: List[str]
        """
        return self._inner_vlan_ids

    @inner_vlan_ids.setter
    def inner_vlan_ids(self, inner_vlan_ids: List[str]):
        """Sets the inner_vlan_ids of this VlanLogicalDoubleTaggedInnerListConfig.


        :param inner_vlan_ids: The inner_vlan_ids of this VlanLogicalDoubleTaggedInnerListConfig.
        :type inner_vlan_ids: List[str]
        """

        self._inner_vlan_ids = inner_vlan_ids
