# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.vlan_logical_match_top_match import VlanLogicalMatchTopMatch  # noqa: F401,E501
from swagger_server import util


class VlanLogicalMatchTop(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, match: VlanLogicalMatchTopMatch=None):  # noqa: E501
        """VlanLogicalMatchTop - a model defined in Swagger

        :param match: The match of this VlanLogicalMatchTop.  # noqa: E501
        :type match: VlanLogicalMatchTopMatch
        """
        self.swagger_types = {
            'match': VlanLogicalMatchTopMatch
        }

        self.attribute_map = {
            'match': 'match'
        }

        self._match = match

    @classmethod
    def from_dict(cls, dikt) -> 'VlanLogicalMatchTop':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VlanLogicalMatchTop of this VlanLogicalMatchTop.  # noqa: E501
        :rtype: VlanLogicalMatchTop
        """
        return util.deserialize_model(dikt, cls)

    @property
    def match(self) -> VlanLogicalMatchTopMatch:
        """Gets the match of this VlanLogicalMatchTop.


        :return: The match of this VlanLogicalMatchTop.
        :rtype: VlanLogicalMatchTopMatch
        """
        return self._match

    @match.setter
    def match(self, match: VlanLogicalMatchTopMatch):
        """Sets the match of this VlanLogicalMatchTop.


        :param match: The match of this VlanLogicalMatchTop.
        :type match: VlanLogicalMatchTopMatch
        """

        self._match = match
