# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VlanConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, status: str=None, name: str=None, vlan_id: str=None):  # noqa: E501
        """VlanConfig - a model defined in Swagger

        :param status: The status of this VlanConfig.  # noqa: E501
        :type status: str
        :param name: The name of this VlanConfig.  # noqa: E501
        :type name: str
        :param vlan_id: The vlan_id of this VlanConfig.  # noqa: E501
        :type vlan_id: str
        """
        self.swagger_types = {
            'status': str,
            'name': str,
            'vlan_id': str
        }

        self.attribute_map = {
            'status': 'status',
            'name': 'name',
            'vlan_id': 'vlanId'
        }

        self._status = status
        self._name = name
        self._vlan_id = vlan_id

    @classmethod
    def from_dict(cls, dikt) -> 'VlanConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VlanConfig of this VlanConfig.  # noqa: E501
        :rtype: VlanConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this VlanConfig.

        Admin state of the VLAN  # noqa: E501

        :return: The status of this VlanConfig.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this VlanConfig.

        Admin state of the VLAN  # noqa: E501

        :param status: The status of this VlanConfig.
        :type status: str
        """
        allowed_values = ["ACTIVE", "SUSPENDED"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def name(self) -> str:
        """Gets the name of this VlanConfig.

        Interface VLAN name.  # noqa: E501

        :return: The name of this VlanConfig.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this VlanConfig.

        Interface VLAN name.  # noqa: E501

        :param name: The name of this VlanConfig.
        :type name: str
        """

        self._name = name

    @property
    def vlan_id(self) -> str:
        """Gets the vlan_id of this VlanConfig.

        Interface VLAN id.  # noqa: E501

        :return: The vlan_id of this VlanConfig.
        :rtype: str
        """
        return self._vlan_id

    @vlan_id.setter
    def vlan_id(self, vlan_id: str):
        """Sets the vlan_id of this VlanConfig.

        Interface VLAN id.  # noqa: E501

        :param vlan_id: The vlan_id of this VlanConfig.
        :type vlan_id: str
        """

        self._vlan_id = vlan_id
