# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.vlan_logical_ingress_mapping_config import VlanLogicalIngressMappingConfig  # noqa: F401,E501
from swagger_server import util


class VlanLogicalIngressMappingTopIngressMapping(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: VlanLogicalIngressMappingConfig=None, config: VlanLogicalIngressMappingConfig=None):  # noqa: E501
        """VlanLogicalIngressMappingTopIngressMapping - a model defined in Swagger

        :param state: The state of this VlanLogicalIngressMappingTopIngressMapping.  # noqa: E501
        :type state: VlanLogicalIngressMappingConfig
        :param config: The config of this VlanLogicalIngressMappingTopIngressMapping.  # noqa: E501
        :type config: VlanLogicalIngressMappingConfig
        """
        self.swagger_types = {
            'state': VlanLogicalIngressMappingConfig,
            'config': VlanLogicalIngressMappingConfig
        }

        self.attribute_map = {
            'state': 'state',
            'config': 'config'
        }

        self._state = state
        self._config = config

    @classmethod
    def from_dict(cls, dikt) -> 'VlanLogicalIngressMappingTopIngressMapping':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VlanLogicalIngressMappingTop_ingressMapping of this VlanLogicalIngressMappingTopIngressMapping.  # noqa: E501
        :rtype: VlanLogicalIngressMappingTopIngressMapping
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> VlanLogicalIngressMappingConfig:
        """Gets the state of this VlanLogicalIngressMappingTopIngressMapping.

        State for ingress VLAN and label behaviors for packets that arrive on this subinterface.  # noqa: E501

        :return: The state of this VlanLogicalIngressMappingTopIngressMapping.
        :rtype: VlanLogicalIngressMappingConfig
        """
        return self._state

    @state.setter
    def state(self, state: VlanLogicalIngressMappingConfig):
        """Sets the state of this VlanLogicalIngressMappingTopIngressMapping.

        State for ingress VLAN and label behaviors for packets that arrive on this subinterface.  # noqa: E501

        :param state: The state of this VlanLogicalIngressMappingTopIngressMapping.
        :type state: VlanLogicalIngressMappingConfig
        """

        self._state = state

    @property
    def config(self) -> VlanLogicalIngressMappingConfig:
        """Gets the config of this VlanLogicalIngressMappingTopIngressMapping.

        Configuration for ingress VLAN and label behaviors for packets that arrive on this subinterface after their VLAN identifier(s) have been matched.  # noqa: E501

        :return: The config of this VlanLogicalIngressMappingTopIngressMapping.
        :rtype: VlanLogicalIngressMappingConfig
        """
        return self._config

    @config.setter
    def config(self, config: VlanLogicalIngressMappingConfig):
        """Sets the config of this VlanLogicalIngressMappingTopIngressMapping.

        Configuration for ingress VLAN and label behaviors for packets that arrive on this subinterface after their VLAN identifier(s) have been matched.  # noqa: E501

        :param config: The config of this VlanLogicalIngressMappingTopIngressMapping.
        :type config: VlanLogicalIngressMappingConfig
        """

        self._config = config
