# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.vlan_routed_config import VlanRoutedConfig  # noqa: F401,E501
from swagger_server.models.vlan_routed_state import VlanRoutedState  # noqa: F401,E501
from swagger_server import util


class VlanRoutedTopRoutedVlan(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: VlanRoutedState=None, config: VlanRoutedConfig=None):  # noqa: E501
        """VlanRoutedTopRoutedVlan - a model defined in Swagger

        :param state: The state of this VlanRoutedTopRoutedVlan.  # noqa: E501
        :type state: VlanRoutedState
        :param config: The config of this VlanRoutedTopRoutedVlan.  # noqa: E501
        :type config: VlanRoutedConfig
        """
        self.swagger_types = {
            'state': VlanRoutedState,
            'config': VlanRoutedConfig
        }

        self.attribute_map = {
            'state': 'state',
            'config': 'config'
        }

        self._state = state
        self._config = config

    @classmethod
    def from_dict(cls, dikt) -> 'VlanRoutedTopRoutedVlan':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VlanRoutedTop_routedVlan of this VlanRoutedTopRoutedVlan.  # noqa: E501
        :rtype: VlanRoutedTopRoutedVlan
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> VlanRoutedState:
        """Gets the state of this VlanRoutedTopRoutedVlan.

        Operational state data   # noqa: E501

        :return: The state of this VlanRoutedTopRoutedVlan.
        :rtype: VlanRoutedState
        """
        return self._state

    @state.setter
    def state(self, state: VlanRoutedState):
        """Sets the state of this VlanRoutedTopRoutedVlan.

        Operational state data   # noqa: E501

        :param state: The state of this VlanRoutedTopRoutedVlan.
        :type state: VlanRoutedState
        """

        self._state = state

    @property
    def config(self) -> VlanRoutedConfig:
        """Gets the config of this VlanRoutedTopRoutedVlan.

        Configuration data for routed vlan interfaces  # noqa: E501

        :return: The config of this VlanRoutedTopRoutedVlan.
        :rtype: VlanRoutedConfig
        """
        return self._config

    @config.setter
    def config(self, config: VlanRoutedConfig):
        """Sets the config of this VlanRoutedTopRoutedVlan.

        Configuration data for routed vlan interfaces  # noqa: E501

        :param config: The config of this VlanRoutedTopRoutedVlan.
        :type config: VlanRoutedConfig
        """

        self._config = config
