# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.vlan_logical_egress_mapping_top_egress_mapping import VlanLogicalEgressMappingTopEgressMapping  # noqa: F401,E501
from swagger_server import util


class VlanLogicalEgressMappingTop(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, egress_mapping: VlanLogicalEgressMappingTopEgressMapping=None):  # noqa: E501
        """VlanLogicalEgressMappingTop - a model defined in Swagger

        :param egress_mapping: The egress_mapping of this VlanLogicalEgressMappingTop.  # noqa: E501
        :type egress_mapping: VlanLogicalEgressMappingTopEgressMapping
        """
        self.swagger_types = {
            'egress_mapping': VlanLogicalEgressMappingTopEgressMapping
        }

        self.attribute_map = {
            'egress_mapping': 'egressMapping'
        }

        self._egress_mapping = egress_mapping

    @classmethod
    def from_dict(cls, dikt) -> 'VlanLogicalEgressMappingTop':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VlanLogicalEgressMappingTop of this VlanLogicalEgressMappingTop.  # noqa: E501
        :rtype: VlanLogicalEgressMappingTop
        """
        return util.deserialize_model(dikt, cls)

    @property
    def egress_mapping(self) -> VlanLogicalEgressMappingTopEgressMapping:
        """Gets the egress_mapping of this VlanLogicalEgressMappingTop.


        :return: The egress_mapping of this VlanLogicalEgressMappingTop.
        :rtype: VlanLogicalEgressMappingTopEgressMapping
        """
        return self._egress_mapping

    @egress_mapping.setter
    def egress_mapping(self, egress_mapping: VlanLogicalEgressMappingTopEgressMapping):
        """Sets the egress_mapping of this VlanLogicalEgressMappingTop.


        :param egress_mapping: The egress_mapping of this VlanLogicalEgressMappingTop.
        :type egress_mapping: VlanLogicalEgressMappingTopEgressMapping
        """

        self._egress_mapping = egress_mapping
