# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VlanTpidConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, tpid: str=None):  # noqa: E501
        """VlanTpidConfig - a model defined in Swagger

        :param tpid: The tpid of this VlanTpidConfig.  # noqa: E501
        :type tpid: str
        """
        self.swagger_types = {
            'tpid': str
        }

        self.attribute_map = {
            'tpid': 'tpid'
        }

        self._tpid = tpid

    @classmethod
    def from_dict(cls, dikt) -> 'VlanTpidConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VlanTpidConfig of this VlanTpidConfig.  # noqa: E501
        :rtype: VlanTpidConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tpid(self) -> str:
        """Gets the tpid of this VlanTpidConfig.

        Optionally set the tag protocol identifier field (TPID) that is accepted on the VLAN  # noqa: E501

        :return: The tpid of this VlanTpidConfig.
        :rtype: str
        """
        return self._tpid

    @tpid.setter
    def tpid(self, tpid: str):
        """Sets the tpid of this VlanTpidConfig.

        Optionally set the tag protocol identifier field (TPID) that is accepted on the VLAN  # noqa: E501

        :param tpid: The tpid of this VlanTpidConfig.
        :type tpid: str
        """

        self._tpid = tpid
