# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.vlan_routed_top_routed_vlan import VlanRoutedTopRoutedVlan  # noqa: F401,E501
from swagger_server import util


class VlanRoutedTop(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, routed_vlan: VlanRoutedTopRoutedVlan=None):  # noqa: E501
        """VlanRoutedTop - a model defined in Swagger

        :param routed_vlan: The routed_vlan of this VlanRoutedTop.  # noqa: E501
        :type routed_vlan: VlanRoutedTopRoutedVlan
        """
        self.swagger_types = {
            'routed_vlan': VlanRoutedTopRoutedVlan
        }

        self.attribute_map = {
            'routed_vlan': 'routedVlan'
        }

        self._routed_vlan = routed_vlan

    @classmethod
    def from_dict(cls, dikt) -> 'VlanRoutedTop':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VlanRoutedTop of this VlanRoutedTop.  # noqa: E501
        :rtype: VlanRoutedTop
        """
        return util.deserialize_model(dikt, cls)

    @property
    def routed_vlan(self) -> VlanRoutedTopRoutedVlan:
        """Gets the routed_vlan of this VlanRoutedTop.


        :return: The routed_vlan of this VlanRoutedTop.
        :rtype: VlanRoutedTopRoutedVlan
        """
        return self._routed_vlan

    @routed_vlan.setter
    def routed_vlan(self, routed_vlan: VlanRoutedTopRoutedVlan):
        """Sets the routed_vlan of this VlanRoutedTop.


        :param routed_vlan: The routed_vlan of this VlanRoutedTop.
        :type routed_vlan: VlanRoutedTopRoutedVlan
        """

        self._routed_vlan = routed_vlan
